In [1]:
"""
This book scraps mockdraftable for all players combine stats from 1999 - 2026
Output is a csv file name 'nfl_combine_df.csv'
"""

"\nThis book scraps mockdraftable for all players combine stats from 1999 - 2026\nOutput is a csv file name 'nfl_combine_df.csv'\n"

In [2]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import re
import time
from pathlib import Path
import os

In [3]:
# Constants

FRACTIONS = {
    "½": ".5", "¼": ".25", "¾": ".75",
    "⅛": ".125", "⅜": ".375", "⅝": ".625", "⅞": ".875",
    "⅓": ".333", "⅔": ".667",
}


PAGE_URL_START_YEAR = 1999
PAGE_URL_END_YEAR = 2026
PAGE_URL_BASE = 'https://www.mockdraftable.com/'
NUMBER_OF_PAGES =  437
LIST_OF_PAGE_URLS = [f'{PAGE_URL_BASE}search?position=ATH&beginYear={PAGE_URL_START_YEAR}&endYear={PAGE_URL_END_YEAR}&sort=DESC&page={page_num}' for page_num in range(1, NUMBER_OF_PAGES+1)]

In [4]:
# Paths

try:
    main_directory = Path(__file__).parent
except NameError:
    main_directory = Path(os.path.dirname(os.getcwd()))  # fallback for Jupyter

data_folder = main_directory / 'data' # data folder output
notebook_folder = main_directory / 'notebooks'

In [5]:
def parse_college_draft(text):
    '''
    Helper function to extract college and draft year from a player card
    '''
    
    if not text:
        return None, None

    parts = [x.strip() for x in text.split(',')]

    if len(parts) == 2:
        return parts[0], parts[1]
    elif len(parts) == 1:
        return None, parts[0]
    else:
        return None, None

def replace_fractions(val: str) -> str:
    '''
    Helper fucntion to get rid of fractions in data
    '''
    for frac, dec in FRACTIONS.items():
        val = val.replace(frac, dec)
    return val


def extract_number(val: str) -> float | None:
    '''
    Strip units/symbols and return a float, or None if unparseable
    '''
    val = str(val).strip()
    if val in ("", "nan", "None", "N/A", "-"):
        return None
    val = replace_fractions(val)
    match = re.search(r"[\d]+\.?[\d]*", val)
    return float(match.group()) if match else None

def parse_height(val: str) -> float | None:
    '''
    Handle Height
    '''
    val = str(val).strip()
    if val in ("", "nan"):
        return None
    val = replace_fractions(val)
    m = re.match(r"(\d+)['\u2019](\d*\.?\d*)", val)   # e.g. 6'4 or 6'4.5
    if m:
        feet, inches = m.groups()
        return int(feet) * 12 + (float(inches) if inches else 0.0)
    m2 = re.search(r"[\d]+\.?[\d]*", val)              # bare number -> inches
    return float(m2.group()) if m2 else None

In [6]:
# Loop through each page and get player_name, draft year, draf position, college, player_id

with requests.Session() as session:
    player_info_dict = {}
    for page_index, page_url in enumerate(LIST_OF_PAGE_URLS):
        page_num = page_index+1
        
        try:
            page_text = session.get(page_url, timeout=10).text
            soup = BeautifulSoup(page_text, 'html.parser')
        except requests.RequestException as e:
            print(f'Failed to access page {page_num} | Error {e}')
            continue  
        
        print(f'{"-"*10} PAGE {page_num} {"-"*10}')
        
        if page_num % 50 == 0:
            pd.DataFrame(player_info_dict.values()).to_csv(data_folder / 'md_progress_backup.csv', index=False)

        # Get table of players
        players_table = soup.find('div', class_ = 'list-group mb-2')
        if not players_table:
            print(f"No table found on page {page_num}")
            continue

        # Get list of player cards from table
        players_cards = players_table.find_all(class_='list-group-item list-group-item-action justify-content-between d-flex')

        # Get Name + player link from player_cards
        for player in players_cards:
            
            span_split_college_draft_class = player.find('span', class_='align-middle ml-2').get_text(strip=True)
            # Base for college + draft
            college, draft_class = parse_college_draft(span_split_college_draft_class) if span_split_college_draft_class else ("",-1) # Get college and draft year

            h5_player_name = player.find('h5', class_='list-group-item-heading mb-0 text-dark')
            player_name = h5_player_name.get_text(strip=True) if h5_player_name else "" # Player's name
            clean_player_name = re.sub('[^A-Za-z0-9]+', '', player_name) if h5_player_name else "" # Strip out everything but letters
            player_id = clean_player_name.lower() + str(draft_class)  if h5_player_name else "" # Create an id clean_name + draft year

            href = player.get('href') # Link to Player page
            if href:
                link_to_players_page = PAGE_URL_BASE + href
            else:
                link_to_players_page = ""
            
            span_draft_position = player.find('span', class_ ='badge') # Draft position
            draft_position = span_draft_position.get('title') if span_draft_position else ""

            # print(f'player_info | {player_name}\n\t player_id {player_id} \n\t link_to_page {link_to_players_page} \n\t draft_position {draft_position} \n\t college {college} \n\t draft_class {draft_class}')

            print(f'\tAdded {player_name}')
            player_dict = {
                'player_name': player_name,
                'player_id' : player_id,
                'player_url': link_to_players_page,
                'draft_class': int(draft_class),
                'position': draft_position,
                'college': college,
            }

            if player_id in player_info_dict:
                continue
            else:
                player_info_dict[player_id] = player_dict
        
        time.sleep(1)
        print(f'\tTotal Players added {len(players_cards)}\n')
        print(f'')
        

    print(f'{"-"*10}\nNum of players added: {len(player_info_dict)}{"-"*10}')


    # else:

---------- PAGE 1 ----------
	Added A'Shawn Robinson
	Added A.C. Leonard
	Added A.J. Brown
	Added A.J. Cann
	Added A.J. Derby
	Added A.J. Edds
	Added A.J. Epenesa
	Added A.J. Green
	Added A.J. Green
	Added A.J. Greene
	Added A.J. Hawk
	Added A.J. Jefferson
	Added A.J. Jenkins
	Added A.J. Klein
	Added A.J. McCarron
	Added A.J. Nicholson
	Added A.J. Stamps
	Added A.J. Terrell
	Added A.Q. Shipley
	Added AJ Barner
	Total Players added 20


---------- PAGE 2 ----------
	Added AJ Haulcy
	Added AT Perry
	Added Aamil Wagner
	Added Aaron  Lynch
	Added Aaron Anderson
	Added Aaron Banks
	Added Aaron Brooks
	Added Aaron Burbridge
	Added Aaron Casey
	Added Aaron Colvin
	Added Aaron Corp
	Added Aaron Curry
	Added Aaron Dalan
	Added Aaron Davis
	Added Aaron Dobson
	Added Aaron Donald
	Added Aaron Fairooz
	Added Aaron Fields
	Added Aaron Francisco
	Added Aaron Fuller
	Total Players added 20


---------- PAGE 3 ----------
	Added Aaron Gibson
	Added Aaron Hansford
	Added Aaron Hester
	Added Aaron Humphrey
	Added Aaron Hunt
	Added Aaron Jones
	Added Aaron Kelly
	Added Aaron Lockett
	Added Aaron Maybin
	Added Aaron Mellette
	Added Aaron Murray
	Added Aaron Parker
	Added Aaron Robinson
	Added Aaron Rodgers
	Added Aaron Ross
	Added Aaron Rouse
	Added Aaron Schobel
	Added Aaron Shea
	Added Aaron Smith
	Added Aaron Stecker
	Total Players added 20


---------- PAGE 4 ----------
	Added Aaron Walker
	Added Aaron Williams
	Added Aaron Williams
	Added Abdual Howard
	Added Abdul Carter
	Added Abdul Hodge
	Added Abraham Elimimian
	Added Abraham Lucas
	Added Abraham Wright
	Added Abram Smith
	Added Abry Jones
	Added Ace Sanders
	Added Adalius Thomas
	Added Adam Archuleta
	Added Adam Bergen
	Added Adam Bishop
	Added Adam Bisnowaty
	Added Adam Carriker
	Added Adam Davis
	Added Adam Gettis
	Total Players added 20


---------- PAGE 5 ----------
	Added Adam Gotsis
	Added Adam Grant
	Added Adam Haayer
	Added Adam Jennings
	Added Adam Kieft
	Added Adam Koets
	Added Adam Korsak
	Added Adam Muema
	Added Adam Randall
	Added Adam Seward
	Added Adam Shaheen
	Added Adam Shead
	Added Adam Snyder
	Added Adam Tafralis
	Added Adam Terry
	Added Adam Thielen
	Added Adam Trautman
	Added Adam Ulatoski
	Added Adarius Bowman
	Added Ade Aruna
	Total Players added 20


---------- PAGE 6 ----------
	Added Adell Duckett
	Added Adetokunbo Ogundeji
	Added Adetomiwa Adebawore
	Added Adisa Isaac
	Added Adolphus Washington
	Added Adonai Mitchell
	Added Adoree' Jackson
	Added Adrian Amos
	Added Adrian Awasom
	Added Adrian Bushell
	Added Adrian Clayborn
	Added Adrian Dingle
	Added Adrian Ealy
	Added Adrian Grady
	Added Adrian Hardy
	Added Adrian Hubbard
	Added Adrian Jones
	Added Adrian Klemm
	Added Adrian Madise
	Added Adrian McPherson
	Total Players added 20


---------- PAGE 7 ----------
	Added Adrian Moten
	Added Adrian Peterson
	Added Adrian Peterson
	Added Adrian Taylor
	Added Adrian Tracy
	Added Adrian Wilson
	Added Adrien Clarke
	Added Adrien Robinson
	Added Aeneas Peebles
	Added Ahkello Witherspoon
	Added Ahmaad Galloway
	Added Ahmaad Moses
	Added Ahmad Black
	Added Ahmad Bradshaw
	Added Ahmad Carroll
	Added Ahmad Childress
	Added Ahmad Dixon
	Added Ahmad Gardner
	Added Ahmari Harvey
	Added Ahmed Hassanein
	Total Players added 20


---------- PAGE 8 ----------
	Added Ahtyba Rubin
	Added Aidan Hubbard
	Added Aidan Hutchinson
	Added Aidan O'Connell
	Added Aiden Fisher
	Added Ainias Smith
	Added Aireontae Ersery
	Added Airese Currie
	Added Aj Dillon
	Added Ajani Cornelius
	Added Akayleb Evans
	Added Akeem Ayers
	Added Akeem Davis-Gaither
	Added Akeem Dent
	Added Akeem Spence
	Added Akheem Mesidor
	Added Akiem Hicks
	Added Akili Smith
	Added Akin Ayodele
	Added Akrum Wadley
	Total Players added 20


---------- PAGE 9 ----------
	Added Akwasi Owusu-Ansah
	Added Al Bond
	Added Al Jackson
	Added Al Lucas
	Added Al Wilson
	Added Al Woods
	Added Al-Quadin Muhammad
	Added Alameda Ta'amu
	Added Alan Ali
	Added Alan Bonner
	Added Alan Branch
	Added Alan Harper
	Added Alan Herron
	Added Alan Reuber
	Added Alani Fua
	Added Alaric Jackson
	Added Albert Huggins
	Added Albert McClellan
	Added Albert Means
	Added Albert Okwuegbunam
	Total Players added 20


---------- PAGE 10 ----------
	Added Albert Regis
	Added Albert Traylor
	Added Albert Wilson
	Added Albrey Battle
	Added Aldon Smith
	Added Aldrick Robinson
	Added Alec Ingold
	Added Alec Lemon
	Added Alec Lindstrom
	Added Alec Ogletree
	Added Alec Pierce
	Added Alex Anzalone
	Added Alex Austin
	Added Alex Bannister
	Added Alex Barnes
	Added Alex Barron
	Added Alex Bars
	Added Alex Boone
	Added Alex Brink
	Added Alex Cappa
	Total Players added 20


---------- PAGE 11 ----------
	Added Alex Carrington
	Added Alex Carter
	Added Alex Collins
	Added Alex Fletcher
	Added Alex Forsyth
	Added Alex Green
	Added Alex Harkey
	Added Alex Haynes
	Added Alex Highsmith
	Added Alex Holmes
	Added Alex Leatherwood
	Added Alex Lewis
	Added Alex Lewis
	Added Alex Lincoln
	Added Alex Linnenkohl
	Added Alex Magee
	Added Alex McCalister
	Added Alex Okafor
	Added Alex Parsons
	Added Alex Pechin
	Total Players added 20


---------- PAGE 12 ----------
	Added Alex Redmond
	Added Alex Smith
	Added Alex Smith
	Added Alex Stepanovich
	Added Alex Sulfsted
	Added Alex Taylor
	Added Alex Wade
	Added Alex Wesley
	Added Alex Wright
	Added Alexander Mattison
	Added Alfonzo Dennard
	Added Alfred Blue
	Added Alfred Collins
	Added Alfred Fincher
	Added Alfred Morris
	Added Alge Crumpler
	Added Ali Gaye
	Added Ali Highsmith
	Added Ali Marpet
	Added Alijah Clark
	Total Players added 20


---------- PAGE 13 ----------
	Added Alijah Holder
	Added Alijah Huzzie
	Added Alijah Vera-Tucker
	Added Alim McNeill
	Added Alize Mack
	Added Allen Bailey
	Added Allen Barbre
	Added Allen Bradford
	Added Allen Hurns
	Added Allen Lazard
	Added Allen Reisner
	Added Allen Robinson
	Added Alohi Gilman
	Added Alontae Taylor
	Added Alonzo Coleman
	Added Alonzo Cunningham
	Added Alonzo Jackson
	Added Alonzo Russell
	Added Alphonso Collins
	Added Alphonso Hodge
	Total Players added 20


---------- PAGE 14 ----------
	Added Alphonso Smith
	Added Alric Arnett
	Added Alshon Jeffery
	Added Alterraun Verner
	Added Alton Robinson
	Added Alton Weaver
	Added Alvin Bailey
	Added Alvin Bowen
	Added Alvin Kamara
	Added Alvin McKinley
	Added Alvin Pearman
	Added Amani Hooker
	Added Amani Oruwariye
	Added Amara Darboh
	Added Amari Cooper
	Added Amari Rodgers
	Added Amari Spievey
	Added Amarius Mims
	Added Amarlo Herrera
	Added Amaré Barno
	Total Players added 20


---------- PAGE 15 ----------
	Added Amba Etta-Tawo
	Added Ambry Thomas
	Added Ameer Abdullah
	Added Amen Ogbongbemiga
	Added Amik Robertson
	Added Amini Silatolu
	Added Amobi Okoye
	Added Amon-Ra St. Brown
	Added Amos Zereoue
	Added Anders Carlson
	Added Andra Davis
	Added Andrae Thurman
	Added Andre  Williams
	Added Andre Branch
	Added Andre Brown
	Added Andre Caldwell
	Added Andre Carter
	Added Andre Carter II
	Added Andre Chachere
	Added Andre Cisco
	Total Players added 20


---------- PAGE 16 ----------
	Added Andre Dillard
	Added Andre Dixon
	Added Andre Ellington
	Added Andre Frazier
	Added Andre Fuller
	Added Andre Gurode
	Added Andre Hal
	Added Andre Hall
	Added Andre Holland
	Added Andre Holmes
	Added Andre James
	Added Andre Johnson
	Added Andre Jones Jr.
	Added Andre King
	Added Andre Maddox
	Added Andre O'Neal
	Added Andre Roberts
	Added Andre Slappey
	Added Andre Smith
	Added Andre Weathers
	Total Players added 20


---------- PAGE 17 ----------
	Added Andre Woolfolk
	Added Andre' Davis
	Added Andre' Sam
	Added Andrei Iosivas
	Added Andrew Armstrong
	Added Andrew Billings
	Added Andrew Booth Jr.
	Added Andrew Brown
	Added Andrew Coker
	Added Andrew Datko
	Added Andrew Donnal
	Added Andrew Jackson
	Added Andrew Jackson
	Added Andrew Kline
	Added Andrew Luck
	Added Andrew McGee
	Added Andrew Means
	Added Andrew Mukuba
	Added Andrew Pinnock
	Added Andrew Quarless
	Total Players added 20


---------- PAGE 18 ----------
	Added Andrew Raym
	Added Andrew Rupcich
	Added Andrew Shull
	Added Andrew Stueber
	Added Andrew Thomas
	Added Andrew Tiller
	Added Andrew Van Ginkel
	Added Andrew Vorhees
	Added Andrew Whitworth
	Added Andrew Williams
	Added Andrew Wingard
	Added Andru Phillips
	Added Andrus Peat
	Added Andy Alleman
	Added Andy Dalton
	Added Andy Eby
	Added Andy Gallik
	Added Andy Isabella
	Added Andy Janovich
	Added Andy Katzenmoyer
	Total Players added 20


---------- PAGE 19 ----------
	Added Andy Kemp
	Added Andy Levitre
	Added Andy Vincent
	Added Anez Cooper
	Added Anfernee Jennings
	Added Anfernee Orji
	Added Angelo Blackson
	Added Angelo Craig
	Added Angelo Crowell
	Added Anim Dankwah
	Added Anquan Boldin
	Added Anthony Adams
	Added Anthony Alabi
	Added Anthony Allen
	Added Anthony Alridge
	Added Anthony Arline
	Added Anthony Averett
	Added Anthony Barr
	Added Anthony Becht
	Added Anthony Belton
	Total Players added 20


---------- PAGE 20 ----------
	Added Anthony Boone
	Added Anthony Bradford
	Added Anthony Brown
	Added Anthony Bryant
	Added Anthony Butler
	Added Anthony Castonzo
	Added Anthony Cesario
	Added Anthony Chickillo
	Added Anthony Collins
	Added Anthony Davis
	Added Anthony Davis
	Added Anthony Davis
	Added Anthony Denham
	Added Anthony Dixon
	Added Anthony Fasano
	Added Anthony Felder
	Added Anthony Fera
	Added Anthony Floyd
	Added Anthony Gonzalez
	Added Anthony Gordon
	Total Players added 20


---------- PAGE 21 ----------
	Added Anthony Gould
	Added Anthony Gray
	Added Anthony Harris
	Added Anthony Henry
	Added Anthony Herron
	Added Anthony Hill
	Added Anthony Hill Jr
	Added Anthony Hines
	Added Anthony Hitchens
	Added Anthony Jefferson
	Added Anthony Johnson
	Added Anthony Johnson
	Added Anthony Johnson
	Added Anthony Johnson Jr.
	Added Anthony Kimble
	Added Anthony Lucas
	Added Anthony Lucas
	Added Anthony Malbrough
	Added Anthony McCoy
	Added Anthony McFarland
	Total Players added 20


---------- PAGE 22 ----------
	Added Anthony McFarland
	Added Anthony Miller
	Added Anthony Mix
	Added Anthony Morelli
	Added Anthony Nelson
	Added Anthony Parker
	Added Anthony Parker
	Added Anthony Pudewell
	Added Anthony Richardson
	Added Anthony Schlegel
	Added Anthony Schwartz
	Added Anthony Sessions
	Added Anthony Sherman
	Added Anthony Smith
	Added Anthony Spencer
	Added Anthony Steen
	Added Anthony Thomas
	Added Anthony Trucks
	Added Anthony Walker Jr.
	Added Anthony Waters
	Total Players added 20


---------- PAGE 23 ----------
	Added Anthony Weaver
	Added Anthony White
	Added Anthony Winbush
	Added Anthony Wright
	Added Anthony Zettel
	Added Antico Dalton
	Added Antjuan Simmons
	Added Antoine Bethea
	Added Antoine Brooks Jr.
	Added Antoine Caldwell
	Added Antoine Cason
	Added Antoine Green
	Added Antoine Harris
	Added Antoine McClain
	Added Antoine Wesley
	Added Antoine Winfield
	Added Antoine Winfield Jr.
	Added Anton Harrison
	Added Anton Palepoi
	Added Antone Exum
	Total Players added 20


---------- PAGE 24 ----------
	Added Antonio  Richardson
	Added Antonio Allen
	Added Antonio Andrews
	Added Antonio Brown
	Added Antonio Bryant
	Added Antonio Callaway
	Added Antonio Cochran
	Added Antonio Coleman
	Added Antonio Cromartie
	Added Antonio Dingle
	Added Antonio Fenelus
	Added Antonio Gandy-Golden
	Added Antonio Garcia
	Added Antonio Gibson
	Added Antonio Hall
	Added Antonio Johnson
	Added Antonio Johnson
	Added Antonio Malone
	Added Antonio Nunn
	Added Antonio Perkins
	Total Players added 20


---------- PAGE 25 ----------
	Added Antonio Phillips
	Added Antonio Pittman
	Added Antonio Smith
	Added Antonio Williams
	Added Antonio Wilson
	Added Antrel Rolle
	Added Anttaj Hawthorne
	Added Antuan Edwards
	Added Antwaan Randle El
	Added Antwan Applewhite
	Added Antwan Barnes
	Added Antwan Davis
	Added Antwan Goodley
	Added Antwan Harris
	Added Antwan Kirk-Hughes
	Added Antwan Lake
	Added Antwan Odom
	Added Antwan Peek
	Added Antwane Wells Jr
	Added Antwaun Molden
	Total Players added 20


---------- PAGE 26 ----------
	Added Antwaun Powell-Ryland
	Added Antwaun Woods
	Added Antwoine Sanders
	Added Antwuan Reed
	Added Aqib Talib
	Added ArDarius Stewart
	Added ArDarius Washington
	Added Arden Key
	Added Arian Foster
	Added Arian Smith
	Added Aric Morris
	Added Aric Williams
	Added Arie Kouandjio
	Added Arik Armstead
	Added Armaj Reed-Adams
	Added Arman Shields
	Added Armand Membou
	Added Armando Allen
	Added Armani Watts
	Added Armon Binns
	Total Players added 20


---------- PAGE 27 ----------
	Added Armon Hatcher
	Added Armon Watts
	Added Armonty Bryant
	Added Arnaz Battle
	Added Arnold Ebiketie
	Added Arnold Miller
	Added Arnold Parker
	Added Arquon Bush
	Added Arrelious Benn
	Added Arryn Siposs
	Added Art Maulet
	Added Artavis Scott
	Added Artayvious Lynn
	Added Arther Love
	Added Arthur Brown
	Added Arthur Lynch
	Added Arthur Moats
	Added Artie Burns
	Added Artis Hicks
	Added Arturo Freeman
	Total Players added 20


---------- PAGE 28 ----------
	Added Arvell Reese
	Added Asa Jackson
	Added Asante Samuel
	Added Asante Samuel
	Added Asher Allen
	Added Ashley Cooper
	Added Ashton Dulin
	Added Ashton Gillotte
	Added Ashton Jeanty
	Added Ashton Lampkin
	Added Ashtyn Davis
	Added Asim Richards
	Added Asim Rose
	Added Atari Bigby
	Added Atcheson Conway
	Added Atiyyah Ellison
	Added Aubrayo Franklin
	Added Auden Tate
	Added Audie Cole
	Added Audric Estimé
	Total Players added 20


---------- PAGE 29 ----------
	Added Augustus Parrish
	Added Aundrae Allison
	Added Austen Lane
	Added Austin Allen
	Added Austin Allen
	Added Austin Barber
	Added Austin Blythe
	Added Austin Booker
	Added Austin Bryant
	Added Austin Collie
	Added Austin Corbett
	Added Austin Davis
	Added Austin Deculus
	Added Austin Duke
	Added Austin Faoliu
	Added Austin Franklin
	Added Austin Hooper
	Added Austin Jackson
	Added Austin Johnson
	Added Austin King
	Total Players added 20


---------- PAGE 30 ----------
	Added Austin Mack
	Added Austin Pettis
	Added Austin Reed
	Added Austin Seferian-Jenkins
	Added Austin Seibert
	Added Austin Shepherd
	Added Austin Watkins
	Added Austin Wheatley
	Added Autry Denson
	Added Avery Gennesy
	Added Avery Moss
	Added Avery Smith
	Added Avery Williams
	Added Avery Williamson
	Added Avery Young
	Added Aviante Collins
	Added Avieon Terrell
	Added Avon Cobourne
	Added Avonte Maddox
	Added Azareye'h Thomas
	Total Players added 20


---------- PAGE 31 ----------
	Added Azeem Victor
	Added Azeez Al-Shaair
	Added Azeez Ojulari
	Added Azur Kamara
	Added B.J. Catalon
	Added B.J. Coleman
	Added B.J. Cunningham
	Added B.J. Dubose
	Added B.J. Finney
	Added B.J. Goodson
	Added B.J. Hill
	Added B.J. Raji
	Added B.J. Tucker
	Added B.W. Webb
	Added BJ Adams
	Added BJ Emmons
	Added BJ Ojulari
	Added BT Potter
	Added Babatunde Oshinowo
	Added Bacarri Rambo
	Total Players added 20


---------- PAGE 32 ----------
	Added Bailey Zappe
	Added Baker Mayfield
	Added Bam Martin-Scott
	Added Baraka Atkins
	Added Barion Brown
	Added Barkevious Mingo
	Added Baron Browning
	Added Barrett Carter
	Added Barrett Green
	Added Barrett Jones
	Added Barrett Ruud
	Added Barrick Nealy
	Added Barry Church
	Added Barry Cofield
	Added Barry Gardner
	Added Barry Richardson
	Added Barryn Sorrell
	Added Bashaud Breeland
	Added Bashir Yamini
	Added Bauer Sharp
	Total Players added 20


---------- PAGE 33 ----------
	Added Baylon Spector
	Added Bear Pascoe
	Added Beau Benzschawel
	Added Beau Brade
	Added Beau Reliford
	Added Beau Sandland
	Added Beau Stephens
	Added Beaux Collins
	Added Beaux Limmer
	Added Behren Morton
	Added Ben Adams
	Added Ben Banogu
	Added Ben Bartch
	Added Ben Boulware
	Added Ben Braden
	Added Ben Braunecker
	Added Ben Bredeson
	Added Ben Brown
	Added Ben Burr-Kirven
	Added Ben Claxton
	Total Players added 20


---------- PAGE 34 ----------
	Added Ben Cleveland
	Added Ben DeLuca
	Added Ben Emanuel
	Added Ben Gedeon
	Added Ben Grubbs
	Added Ben Hamilton
	Added Ben Hartsock
	Added Ben Heeney
	Added Ben Johnson
	Added Ben Jones
	Added Ben Kelly
	Added Ben Koyack
	Added Ben Leber
	Added Ben Mason
	Added Ben Miller
	Added Ben Nichols
	Added Ben Obomanu
	Added Ben Obomanu
	Added Ben Patrick
	Added Ben Powers
	Total Players added 20


---------- PAGE 35 ----------
	Added Ben Roethlisberger
	Added Ben Sinnott
	Added Ben Sobieski
	Added Ben Tate
	Added Ben Taylor
	Added Ben Victor
	Added Ben Watson
	Added BenJarvus Green-Ellis
	Added Benard Thomas
	Added Benardrick McKinney
	Added Bene  Benwikere
	Added Beniquez Brown
	Added Benito Jones
	Added Benjamin Morrison
	Added Benjamin St-Juste
	Added Bennett Jackson
	Added Bennett Skowronek
	Added Bennie Fowler
	Added Bennie Joppru
	Added Bennie Logan
	Total Players added 20


---------- PAGE 36 ----------
	Added Benny Lemay
	Added Benny Snell
	Added Bernard Berrian
	Added Bernard Morris
	Added Bernard Pierce
	Added Bernard Pollard
	Added Bernard Robertson
	Added Bernard Scott
	Added Bernhard Raimann
	Added Bethel Johnson
	Added Bhawoh Jue
	Added Bhayshul Tuten
	Added Bijan Robinson
	Added Bilal Nichols
	Added Bilal Powell
	Added Bilhal Kone
	Added Bill Burke
	Added Bill Ferrario
	Added Bill Swancutt
	Added Billy Baber
	Total Players added 20


---------- PAGE 37 ----------
	Added Billy Bajema
	Added Billy Bowman Jr.
	Added Billy Brown
	Added Billy Gustin
	Added Billy Miller
	Added Billy Price
	Added Billy Schrauth
	Added Billy Strother
	Added Billy Turner
	Added Billy Winn
	Added Bishop Fitzgerald
	Added Bishop Sankey
	Added Bisi Johnson
	Added Bjoern Werner
	Added Blace Brown
	Added Blaine Gabbert
	Added Blair Brown
	Added Blair Phillips
	Added Blair White
	Added Blaise Andries
	Total Players added 20


---------- PAGE 38 ----------
	Added Blake Bell
	Added Blake Bortles
	Added Blake Cashman
	Added Blake Corum
	Added Blake Ferguson
	Added Blake Fisher
	Added Blake Freeland
	Added Blake Gallagher
	Added Blake Martinez
	Added Blake Miller
	Added Blake Proehl
	Added Blake Sims
	Added Blake Whiteheart
	Added Blessuan Austin
	Added Blidi Wreh-Wilson
	Added Bo Melton
	Added Bo Nix
	Added Bo Scaife
	Added Bo Scarbrough
	Added Bo Schobel
	Total Players added 20


---------- PAGE 39 ----------
	Added Bo Smith
	Added Bob Sanders
	Added Bobbie Howard
	Added Bobby Blizzard
	Added Bobby Brown
	Added Bobby Evans
	Added Bobby Gray
	Added Bobby Hart
	Added Bobby Jackson
	Added Bobby Jamison-Travis
	Added Bobby Massie
	Added Bobby McCain
	Added Bobby McCray
	Added Bobby Myers
	Added Bobby Newcombe
	Added Bobby Okereke
	Added Bobby Purify
	Added Bobby Richardson
	Added Bobby Singh
	Added Bobby Sippio
	Total Players added 20


---------- PAGE 40 ----------
	Added Bobby Wade
	Added Bobby Wagner
	Added Bobby Williams
	Added Bobo Wilson
	Added Boo Williams
	Added Boomer Grigsby
	Added Bopete Keyes
	Added Boris Lee
	Added Boseko Lokombo
	Added Boss Bailey
	Added Boye Mafe
	Added Brad Banks
	Added Brad Bedell
	Added Brad Cottam
	Added Brad Kaaya
	Added Brad Lekkerkerker
	Added Brad Meester
	Added Brad Robbins
	Added Brad Scioli
	Added Brad Smith
	Total Players added 20


---------- PAGE 41 ----------
	Added Brad Sorensen
	Added Brad Stewart
	Added Brad Ware
	Added Brad Winn
	Added Braden Brown
	Added Braden Fiske
	Added Braden Mann
	Added Braden Smith
	Added Braden Wilson
	Added Bradie James
	Added Bradlee Anae
	Added Bradlee Van Pelt
	Added Bradley Chubb
	Added Bradley Fletcher
	Added Bradley McDougald
	Added Bradley Roby
	Added Brady Breeze
	Added Brady Christensen
	Added Brady Cook
	Added Brady Davis
	Total Players added 20


---------- PAGE 42 ----------
	Added Brady Latham
	Added Brady Poppinga
	Added Brady Quinn
	Added Brady White
	Added Bradyn Swinson
	Added Braeden Daniels
	Added Braelon Allen
	Added Braiden McGregor
	Added Bralen Trice
	Added Bralon Addison
	Added Branden Albert
	Added Branden Jackson
	Added Branden Ore
	Added Brandin Cooks
	Added Brandin Echols
	Added Brandon Aiyuk
	Added Brandon Allen
	Added Brandon Bair
	Added Brandon Bolden
	Added Brandon Boykin
	Total Players added 20


---------- PAGE 43 ----------
	Added Brandon Breazell
	Added Brandon Bridge
	Added Brandon Browner
	Added Brandon Bulsworth

In [7]:
display(player_info_dict)

{'ashawnrobinson2016': {'player_name': "A'Shawn Robinson",
  'player_id': 'ashawnrobinson2016',
  'player_url': 'https://www.mockdraftable.com//player/ashawn-robinson?position=ATH',
  'draft_class': 2016,
  'position': 'Defensive Tackle',
  'college': 'Alabama'},
 'acleonard2014': {'player_name': 'A.C. Leonard',
  'player_id': 'acleonard2014',
  'player_url': 'https://www.mockdraftable.com//player/ac-leonard?position=ATH',
  'draft_class': 2014,
  'position': 'Tight End',
  'college': 'Tennessee State'},
 'ajbrown2019': {'player_name': 'A.J. Brown',
  'player_id': 'ajbrown2019',
  'player_url': 'https://www.mockdraftable.com//player/aj-brown?position=ATH',
  'draft_class': 2019,
  'position': 'Wide Receiver',
  'college': 'Ole Miss'},
 'ajcann2015': {'player_name': 'A.J. Cann',
  'player_id': 'ajcann2015',
  'player_url': 'https://www.mockdraftable.com//player/aj-cann?position=ATH',
  'draft_class': 2015,
  'position': 'Offensive Guard',
  'college': 'South Carolina'},
 'ajderby2015': {'player_name': 'A.J. Derby',
  'player_id': 'ajderby2015',
  'player_url': 'https://www.mockdraftable.com//player/aj-derby?position=ATH',
  'draft_class': 2015,
  'position': 'Tight End',
  'college': 'Arkansas'},
 'ajedds2010': {'player_name': 'A.J. Edds',
  'player_id': 'ajedds2010',
  'player_url': 'https://www.mockdraftable.com//player/aj-edds?position=ATH',
  'draft_class': 2010,
  'position': 'Outside Linebacker',
  'college': 'Iowa'},
 'ajepenesa2020': {'player_name': 'A.J. Epenesa',
  'player_id': 'ajepenesa2020',
  'player_url': 'https://www.mockdraftable.com//player/aj-epenesa?position=ATH',
  'draft_class': 2020,
  'position': 'Defensive Line',
  'college': 'Iowa'},
 'ajgreen2020': {'player_name': 'A.J. Green',
  'player_id': 'ajgreen2020',
  'player_url': 'https://www.mockdraftable.com//player/aj-green-2020?position=ATH',
  'draft_class': 2020,
  'position': 'Cornerback',
  'college': 'Oklahoma State'},
 'ajgreen2011': {'player_name': 'A.J. Green',
  'player_id': 'ajgreen2011',
  'player_url': 'https://www.mockdraftable.com//player/aj-green?position=ATH',
  'draft_class': 2011,
  'position': 'Wide Receiver',
  'college': 'Georgia'},
 'ajgreene2012': {'player_name': 'A.J. Greene',
  'player_id': 'ajgreene2012',
  'player_url': 'https://www.mockdraftable.com//player/aj-greene?position=ATH',
  'draft_class': 2012,
  'position': 'Offensive Tackle',
  'college': 'Auburn'},
 'ajhawk2006': {'player_name': 'A.J. Hawk',
  'player_id': 'ajhawk2006',
  'player_url': 'https://www.mockdraftable.com//player/aj-hawk?position=ATH',
  'draft_class': 2006,
  'position': 'Outside Linebacker',
  'college': 'Ohio State'},
 'ajjefferson2010': {'player_name': 'A.J. Jefferson',
  'player_id': 'ajjefferson2010',
  'player_url': 'https://www.mockdraftable.com//player/aj-jefferson?position=ATH',
  'draft_class': 2010,
  'position': 'Cornerback',
  'college': 'Fresno State'},
 'ajjenkins2012': {'player_name': 'A.J. Jenkins',
  'player_id': 'ajjenkins2012',
  'player_url': 'https://www.mockdraftable.com//player/aj-jenkins?position=ATH',
  'draft_class': 2012,
  'position': 'Wide Receiver',
  'college': 'Illinois'},
 'ajklein2013': {'player_name': 'A.J. Klein',
  'player_id': 'ajklein2013',
  'player_url': 'https://www.mockdraftable.com//player/aj-klein?position=ATH',
  'draft_class': 2013,
  'position': 'Inside Linebacker',
  'college': 'Iowa State'},
 'ajmccarron2014': {'player_name': 'A.J. McCarron',
  'player_id': 'ajmccarron2014',
  'player_url': 'https://www.mockdraftable.com//player/aj-mccarron?position=ATH',
  'draft_class': 2014,
  'position': 'Quarterback',
  'college': 'Alabama'},
 'ajnicholson2006': {'player_name': 'A.J. Nicholson',
  'player_id': 'ajnicholson2006',
  'player_url': 'https://www.mockdraftable.com//player/aj-nicholson?position=ATH',
  'draft_class': 2006,
  'position': 'Outside Linebacker',
  'college': 'Florida State'},
 'ajstamps2016': {'player_name': 'A.J. Stamps',
  'player_id': 'ajstamps2016',
  'player_url': 'https://www.mockdraftable.com//player/aj-stamps?position=ATH',
  'draft_class': 2016,
  'position': 'Safety',
  'college': 'Kentucky'},
 'ajterrell2020': {'player_name': 'A.J. Terrell',
  'player_id': 'ajterrell2020',
  'player_url': 'https://www.mockdraftable.com//player/aj-terrell?position=ATH',
  'draft_class': 2020,
  'position': 'Cornerback',
  'college': 'Clemson'},
 'aqshipley2009': {'player_name': 'A.Q. Shipley',
  'player_id': 'aqshipley2009',
  'player_url': 'https://www.mockdraftable.com//player/aq-shipley?position=ATH',
  'draft_class': 2009,
  'position': 'Offensive Center',
  'college': 'Penn State'},
 'ajbarner2024': {'player_name': 'AJ Barner',
  'player_id': 'ajbarner2024',
  'player_url': 'https://www.mockdraftable.com//player/aj-barner?position=ATH',
  'draft_class': 2024,
  'position': 'Tight End',
  'college': 'Michigan'},
 'ajhaulcy2026': {'player_name': 'AJ Haulcy',
  'player_id': 'ajhaulcy2026',
  'player_url': 'https://www.mockdraftable.com//player/aj-haulcy?position=ATH',
  'draft_class': 2026,
  'position': 'Safety',
  'college': 'LSU'},
 'atperry2023': {'player_name': 'AT Perry',
  'player_id': 'atperry2023',
  'player_url': 'https://www.mockdraftable.com//player/at-perry?position=ATH',
  'draft_class': 2023,
  'position': 'Wide Receiver',
  'college': 'Wake Forest'},
 'aamilwagner2026': {'player_name': 'Aamil Wagner',
  'player_id': 'aamilwagner2026',
  'player_url': 'https://www.mockdraftable.com//player/aamil-wagner?position=ATH',
  'draft_class': 2026,
  'position': 'Offensive Tackle',
  'college': 'Notre Dame'},
 'aaronlynch2014': {'player_name': 'Aaron  Lynch',
  'player_id': 'aaronlynch2014',
  'player_url': 'https://www.mockdraftable.com//player/aaron-lynch?position=ATH',
  'draft_class': 2014,
  'position': 'One-Gap Defensive End',
  'college': 'South Florida'},
 'aaronanderson2026': {'player_name': 'Aaron Anderson',
  'player_id': 'aaronanderson2026',
  'player_url': 'https://www.mockdraftable.com//player/aaron-anderson?position=ATH',
  'draft_class': 2026,
  'position': 'Wide Receiver',
  'college': 'LSU'},
 'aaronbanks2021': {'player_name': 'Aaron Banks',
  'player_id': 'aaronbanks2021',
  'player_url': 'https://www.mockdraftable.com//player/aaron-banks?position=ATH',
  'draft_class': 2021,
  'position': 'Offensive Guard',
  'college': 'Notre Dame'},
 'aaronbrooks1999': {'player_name': 'Aaron Brooks',
  'player_id': 'aaronbrooks1999',
  'player_url': 'https://www.mockdraftable.com//player/aaron-brooks?position=ATH',
  'draft_class': 1999,
  'position': 'Quarterback',
  'college': 'Virginia'},
 'aaronburbridge2016': {'player_name': 'Aaron Burbridge',
  'player_id': 'aaronburbridge2016',
  'player_url': 'https://www.mockdraftable.com//player/aaron-burbridge?position=ATH',
  'draft_class': 2016,
  'position': 'Wide Receiver',
  'college': 'Michigan State'},
 'aaroncasey2024': {'player_name': 'Aaron Casey',
  'player_id': 'aaroncasey2024',
  'player_url': 'https://www.mockdraftable.com//player/aaron-casey?position=ATH',
  'draft_class': 2024,
  'position': 'Linebacker',
  'college': 'Indiana'},
 'aaroncolvin2014': {'player_name': 'Aaron Colvin',
  'player_id': 'aaroncolvin2014',
  'player_url': 'https://www.mockdraftable.com//player/aaron-colvin?position=ATH',
  'draft_class': 2014,
  'position': 'Cornerback',
  'college': 'Oklahoma'},
 'aaroncorp2012': {'player_name': 'Aaron Corp',
  'player_id': 'aaroncorp2012',
  'player_url': 'https://www.mockdraftable.com//player/aaron-corp?position=ATH',
  'draft_class': 2012,
  'position': 'Quarterback',
  'college': 'Richmond'},
 'aaroncurry2009': {'player_name': 'Aaron Curry',
  'player_id': 'aaroncurry2009',
  'player_url': 'https://www.mockdraftable.com//player/aaron-curry?position=ATH',
  'draft_class': 2009,
  'position': 'Outside Linebacker',
  'college': 'Wake Forest'},
 'aarondalan1999': {'player_name': 'Aaron Dalan',
  'player_id': 'aarondalan1999',
  'player_url': 'https://www.mockdraftable.com//player/aaron-dalan?position=ATH',
  'draft_class': 1999,
  'position': 'Offensive Tackle',
  'college': 'Washington'},
 'aarondavis2015': {'player_name': 'Aaron Davis',
  'player_id': 'aarondavis2015',
  'player_url': 'https://www.mockdraftable.com//player/aaron-davis?position=ATH',
  'draft_class': 2015,
  'position': 'Outside Linebacker',
  'college': 'Colorado State'},
 'aarondobson2013': {'player_name': 'Aaron Dobson',
  'player_id': 'aarondobson2013',
  'player_url': 'https://www.mockdraftable.com//player/aaron-dobson?position=ATH',
  'draft_class': 2013,
  'position': 'Wide Receiver',
  'college': 'Marshall'},
 'aarondonald2014': {'player_name': 'Aaron Donald',
  'player_id': 'aarondonald2014',
  'player_url': 'https://www.mockdraftable.com//player/aaron-donald?position=ATH',
  'draft_class': 2014,
  'position': 'Defensive Tackle',
  'college': 'Pittsburgh'},
 'aaronfairooz2007': {'player_name': 'Aaron Fairooz',
  'player_id': 'aaronfairooz2007',
  'player_url': 'https://www.mockdraftable.com//player/aaron-fairooz?position=ATH',
  'draft_class': 2007,
  'position': 'Wide Receiver',
  'college': 'Central Arkansas'},
 'aaronfields2000': {'player_name': 'Aaron Fields',
  'player_id': 'aaronfields2000',
  'player_url': 'https://www.mockdraftable.com//player/aaron-fields?position=ATH',
  'draft_class': 2000,
  'position': 'One-Gap Defensive End',
  'college': 'Troy'},
 'aaronfrancisco2005': {'player_name': 'Aaron Francisco',
  'player_id': 'aaronfrancisco2005',
  'player_url': 'https://www.mockdraftable.com//player/aaron-francisco?position=ATH',
  'draft_class': 2005,
  'position': 'Safety',
  'college': 'BYU'},
 'aaronfuller2020': {'player_name': 'Aaron Fuller',
  'player_id': 'aaronfuller2020',
  'player_url': 'https://www.mockdraftable.com//player/aaron-fuller?position=ATH',
  'draft_class': 2020,
  'position': 'Wide Receiver',
  'college': 'Washington'},
 'aarongibson1999': {'player_name': 'Aaron Gibson',
  'player_id': 'aarongibson1999',
  'player_url': 'https://www.mockdraftable.com//player/aaron-gibson?position=ATH',
  'draft_class': 1999,
  'position': 'Offensive Tackle',
  'college': 'Wisconsin'},
 'aaronhansford2022': {'player_name': 'Aaron Hansford',
  'player_id': 'aaronhansford2022',
  'player_url': 'https://www.mockdraftable.com//player/aaron-hansford?position=ATH',
  'draft_class': 2022,
  'position': 'Linebacker',
  'college': 'Texas A&M'},
 'aaronhester2013': {'player_name': 'Aaron Hester',
  'player_id': 'aaronhester2013',
  'player_url': 'https://www.mockdraftable.com//player/aaron-hester?position=ATH',
  'draft_class': 2013,
  'position': 'Cornerback',
  'college': 'UCLA'},
 'aaronhumphrey2000': {'player_name': 'Aaron Humphrey',
  'player_id': 'aaronhumphrey2000',
  'player_url': 'https://www.mockdraftable.com//player/aaron-humphrey?position=ATH',
  'draft_class': 2000,
  'position': 'One-Gap Defensive End',
  'college': 'Texas'},
 'aaronhunt2003': {'player_name': 'Aaron Hunt',
  'player_id': 'aaronhunt2003',
  'player_url': 'https://www.mockdraftable.com//player/aaron-hunt?position=ATH',
  'draft_class': 2003,
  'position': 'One-Gap Defensive End',
  'college': 'Texas Tech'},
 'aaronjones2017': {'player_name': 'Aaron Jones',
  'player_id': 'aaronjones2017',
  'player_url': 'https://www.mockdraftable.com//player/aaron-jones?position=ATH',
  'draft_class': 2017,
  'position': 'Halfback',
  'college': 'Texas-El Paso'},
 'aaronkelly2009': {'player_name': 'Aaron Kelly',
  'player_id': 'aaronkelly2009',
  'player_url': 'https://www.mockdraftable.com//player/aaron-kelly?position=ATH',
  'draft_class': 2009,
  'position': 'Wide Receiver',
  'college': 'Clemson'},
 'aaronlockett2002': {'player_name': 'Aaron Lockett',
  'player_id': 'aaronlockett2002',
  'player_url': 'https://www.mockdraftable.com//player/aaron-lockett?position=ATH',
  'draft_class': 2002,
  'position': 'Wide Receiver',
  'college': 'Kansas State'},
 'aaronmaybin2009': {'player_name': 'Aaron Maybin',
  'player_id': 'aaronmaybin2009',
  'player_url': 'https://www.mockdraftable.com//player/aaron-maybin?position=ATH',
  'draft_class': 2009,
  'position': 'One-Gap Defensive End',
  'college': 'Penn State'},
 'aaronmellette2013': {'player_name': 'Aaron Mellette',
  'player_id': 'aaronmellette2013',
  'player_url': 'https://www.mockdraftable.com//player/aaron-mellette?position=ATH',
  'draft_class': 2013,
  'position': 'Wide Receiver',
  'college': 'Elon'},
 'aaronmurray2014': {'player_name': 'Aaron Murray',
  'player_id': 'aaronmurray2014',
  'player_url': 'https://www.mockdraftable.com//player/aaron-murray?position=ATH',
  'draft_class': 2014,
  'position': 'Quarterback',
  'college': 'Georgia'},
 'aaronparker2020': {'player_name': 'Aaron Parker',
  'player_id': 'aaronparker2020',
  'player_url': 'https://www.mockdraftable.com//player/aaron-parker?position=ATH',
  'draft_class': 2020,
  'position': 'Wide Receiver',
  'college': 'Rhode Island'},
 'aaronrobinson2021': {'player_name': 'Aaron Robinson',
  'player_id': 'aaronrobinson2021',
  'player_url': 'https://www.mockdraftable.com//player/aaron-robinson?position=ATH',
  'draft_class': 2021,
  'position': 'Cornerback',
  'college': 'Central Florida'},
 'aaronrodgers2005': {'player_name': 'Aaron Rodgers',
  'player_id': 'aaronrodgers2005',
  'player_url': 'https://www.mockdraftable.com//player/aaron-rodgers?position=ATH',
  'draft_class': 2005,
  'position': 'Quarterback',
  'college': 'California'},
 'aaronross2007': {'player_name': 'Aaron Ross',
  'player_id': 'aaronross2007',
  'player_url': 'https://www.mockdraftable.com//player/aaron-ross?position=ATH',
  'draft_class': 2007,
  'position': 'Cornerback',
  'college': 'Texas'},
 'aaronrouse2007': {'player_name': 'Aaron Rouse',
  'player_id': 'aaronrouse2007',
  'player_url': 'https://www.mockdraftable.com//player/aaron-rouse?position=ATH',
  'draft_class': 2007,
  'position': 'Safety',
  'college': 'Virginia Tech'},
 'aaronschobel2001': {'player_name': 'Aaron Schobel',
  'player_id': 'aaronschobel2001',
  'player_url': 'https://www.mockdraftable.com//player/aaron-schobel?position=ATH',
  'draft_class': 2001,
  'position': 'One-Gap Defensive End',
  'college': 'TCU'},
 'aaronshea2000': {'player_name': 'Aaron Shea',
  'player_id': 'aaronshea2000',
  'player_url': 'https://www.mockdraftable.com//player/aaron-shea?position=ATH',
  'draft_class': 2000,
  'position': 'Fullback',
  'college': 'Michigan'},
 'aaronsmith1999': {'player_name': 'Aaron Smith',
  'player_id': 'aaronsmith1999',
  'player_url': 'https://www.mockdraftable.com//player/aaron-smith?position=ATH',
  'draft_class': 1999,
  'position': 'One-Gap Defensive End',
  'college': 'Northern Colorado'},
 'aaronstecker1999': {'player_name': 'Aaron Stecker',
  'player_id': 'aaronstecker1999',
  'player_url': 'https://www.mockdraftable.com//player/aaron-stecker?position=ATH',
  'draft_class': 1999,
  'position': 'Halfback',
  'college': 'Western Illinois'},
 'aaronwalker2003': {'player_name': 'Aaron Walker',
  'player_id': 'aaronwalker2003',
  'player_url': 'https://www.mockdraftable.com//player/aaron-walker?position=ATH',
  'draft_class': 2003,
  'position': 'Tight End',
  'college': 'Florida'},
 'aaronwilliams2011': {'player_name': 'Aaron Williams',
  'player_id': 'aaronwilliams2011',
  'player_url': 'https://www.mockdraftable.com//player/aaron-williams-2011?position=ATH',
  'draft_class': 2011,
  'position': 'Cornerback',
  'college': 'Texas'},
 'aaronwilliams1999': {'player_name': 'Aaron Williams',
  'player_id': 'aaronwilliams1999',
  'player_url': 'https://www.mockdraftable.com//player/aaron-williams?position=ATH',
  'draft_class': 1999,
  'position': 'One-Gap Defensive End',
  'college': 'Indiana'},
 'abdualhoward2002': {'player_name': 'Abdual Howard',
  'player_id': 'abdualhoward2002',
  'player_url': 'https://www.mockdraftable.com//player/abdual-howard?position=ATH',
  'draft_class': 2002,
  'position': 'Safety',
  'college': 'Florida State'},
 'abdulcarter2025': {'player_name': 'Abdul Carter',
  'player_id': 'abdulcarter2025',
  'player_url': 'https://www.mockdraftable.com//player/abdul-carter?position=ATH',
  'draft_class': 2025,
  'position': 'Defensive Line',
  'college': 'Penn State'},
 'abdulhodge2006': {'player_name': 'Abdul Hodge',
  'player_id': 'abdulhodge2006',
  'player_url': 'https://www.mockdraftable.com//player/abdul-hodge?position=ATH',
  'draft_class': 2006,
  'position': 'Inside Linebacker',
  'college': 'Iowa'},
 'abrahamelimimian2005': {'player_name': 'Abraham Elimimian',
  'player_id': 'abrahamelimimian2005',
  'player_url': 'https://www.mockdraftable.com//player/abraham-elimimian?position=ATH',
  'draft_class': 2005,
  'position': 'Cornerback',
  'college': "Hawai'i"},
 'abrahamlucas2022': {'player_name': 'Abraham Lucas',
  'player_id': 'abrahamlucas2022',
  'player_url': 'https://www.mockdraftable.com//player/abraham-lucas?position=ATH',
  'draft_class': 2022,
  'position': 'Offensive Line',
  'college': 'Washington State'},
 'abrahamwright2007': {'player_name': 'Abraham Wright',
  'player_id': 'abrahamwright2007',
  'player_url': 'https://www.mockdraftable.com//player/abraham-wright?position=ATH',
  'draft_class': 2007,
  'position': 'One-Gap Defensive End',
  'college': 'Colorado'},
 'abramsmith2022': {'player_name': 'Abram Smith',
  'player_id': 'abramsmith2022',
  'player_url': 'https://www.mockdraftable.com//player/abram-smith?position=ATH',
  'draft_class': 2022,
  'position': 'Halfback',
  'college': 'Baylor'},
 'abryjones2013': {'player_name': 'Abry Jones',
  'player_id': 'abryjones2013',
  'player_url': 'https://www.mockdraftable.com//player/abry-jones?position=ATH',
  'draft_class': 2013,
  'position': 'Defensive Tackle',
  'college': 'Georgia'},
 'acesanders2013': {'player_name': 'Ace Sanders',
  'player_id': 'acesanders2013',
  'player_url': 'https://www.mockdraftable.com//player/ace-sanders?position=ATH',
  'draft_class': 2013,
  'position': 'Wide Receiver',
  'college': 'South Carolina'},
 'adaliusthomas2000': {'player_name': 'Adalius Thomas',
  'player_id': 'adaliusthomas2000',
  'player_url': 'https://www.mockdraftable.com//player/adalius-thomas?position=ATH',
  'draft_class': 2000,
  'position': 'One-Gap Defensive End',
  'college': 'Southern Miss'},
 'adamarchuleta2001': {'player_name': 'Adam Archuleta',
  'player_id': 'adamarchuleta2001',
  'player_url': 'https://www.mockdraftable.com//player/adam-archuleta?position=ATH',
  'draft_class': 2001,
  'position': 'Safety',
  'college': 'Arizona State'},
 'adambergen2005': {'player_name': 'Adam Bergen',
  'player_id': 'adambergen2005',
  'player_url': 'https://www.mockdraftable.com//player/adam-bergen?position=ATH',
  'draft_class': 2005,
  'position': 'Tight End',
  'college': 'Lehigh'},
 'adambishop2008': {'player_name': 'Adam Bishop',
  'player_id': 'adambishop2008',
  'player_url': 'https://www.mockdraftable.com//player/adam-bishop?position=ATH',
  'draft_class': 2008,
  'position': 'Tight End',
  'college': 'Nevada'},
 'adambisnowaty2017': {'player_name': 'Adam Bisnowaty',
  'player_id': 'adambisnowaty2017',
  'player_url': 'https://www.mockdraftable.com//player/adam-bisnowaty?position=ATH',
  'draft_class': 2017,
  'position': 'Offensive Tackle',
  'college': 'Pittsburgh'},
 'adamcarriker2007': {'player_name': 'Adam Carriker',
  'player_id': 'adamcarriker2007',
  'player_url': 'https://www.mockdraftable.com//player/adam-carriker?position=ATH',
  'draft_class': 2007,
  'position': 'One-Gap Defensive End',
  'college': 'Nebraska'},
 'adamdavis2000': {'player_name': 'Adam Davis',
  'player_id': 'adamdavis2000',
  'player_url': 'https://www.mockdraftable.com//player/adam-davis?position=ATH',
  'draft_class': 2000,
  'position': 'Offensive Guard',
  'college': 'Oklahoma State'},
 'adamgettis2012': {'player_name': 'Adam Gettis',
  'player_id': 'adamgettis2012',
  'player_url': 'https://www.mockdraftable.com//player/adam-gettis?position=ATH',
  'draft_class': 2012,
  'position': 'Offensive Guard',
  'college': 'Iowa'},
 'adamgotsis2016': {'player_name': 'Adam Gotsis',
  'player_id': 'adamgotsis2016',

In [8]:
# Loop through each player page and extract height, wieght, arm length, hand size, 40 yard dash, vert jump, broad jump, bench press

with requests.Session() as session:
    for player_id in player_info_dict:
            player_url = player_info_dict[player_id]['player_url']
            player_name = player_info_dict[player_id]['player_name']
            try:
                player_page_text = session.get(player_url, timeout=10).text
            except requests.RequestException as e:
                 print(f'Failed to access player page for {player_name} | {e}')
                 continue
            
            time.sleep(0.5)
            player_soup = BeautifulSoup(player_page_text, 'html.parser')
            player_measurements_table  = player_soup.find('table', class_ = 'table table-sm mb-0')
            if not player_measurements_table:
                 print(f'No Measurements found for {player_name}')
                 continue
            measurements_list = player_measurements_table.find_all('tr')

            print(f'{"-"*10} {player_name.upper()}')
            for measurement in measurements_list[1:]:
                line_items = measurement.find_all('td')
                measurement_name = line_items[0].get_text(strip=True).lower()
                value = line_items[1].get_text(strip=True)

                print(f'{measurement_name} | {value}')
                player_info_dict[player_id][measurement_name] = value
                # print(measurement)
            # counter += 1

        # player_dict = {}

---------- A'SHAWN ROBINSON
height | 6' 4"
weight | 307 lbs
arm length | 34½"
hand size | 10½"
10 yard split | 1.78s
40 yard dash | 5.2s
vertical jump | 26"
broad jump | 106"
3-cone drill | 7.8s
20 yard shuttle | 4.74s
bench press | 22 reps
---------- A.C. LEONARD
height | 6' 2"
weight | 252 lbs
arm length | 33"
hand size | 9¼"
40 yard dash | 4.5s
vertical jump | 34"
broad jump | 128"
bench press | 20 reps
---------- A.J. BROWN
height | 6' 0½"
weight | 226 lbs
wingspan | 78"
arm length | 32⅞"
hand size | 9¾"
40 yard dash | 4.49s
vertical jump | 36½"
broad jump | 120"
bench press | 19 reps
---------- A.J. CANN
height | 6' 3"
weight | 313 lbs
arm length | 32⅝"
hand size | 10¼"
bench press | 26 reps
---------- A.J. DERBY
height | 6' 4"
weight | 255 lbs
arm length | 30½"
hand size | 9½"
bench press | 15 reps
---------- A.J. EDDS
height | 6' 4"
weight | 246 lbs
arm length | 32¾"
hand size | 9⅛"
10 yard split | 1.6s
40 yard dash | 4.62s
vertical jump | 33"
broad jump | 117"
3-cone drill | 7.19s
20 yard shuttle | 4.28s
bench press | 16 reps
---------- A.J. EPENESA
height | 6' 5"
weight | 275 lbs
arm length | 34½"
hand size | 10⅛"
40 yard dash | 5.04s
vertical jump | 32½"
broad jump | 117"
3-cone drill | 7.34s
20 yard shuttle | 4.46s
bench press | 17 reps
---------- A.J. GREEN
height | 6' 1"
weight | 202 lbs
arm length | 30⅞"
hand size | 9"
40 yard dash | 4.62s
bench press | 13 reps
---------- A.J. GREEN
height | 6' 4"
weight | 211 lbs
arm length | 34⅜"
hand size | 9¼"
10 yard split | 1.55s
20 yard split | 2.53s
40 yard dash | 4.48s
vertical jump | 34½"
broad jump | 126"
3-cone drill | 6.91s
20 yard shuttle | 4.21s
60 yard shuttle | 11.46s
bench press | 18 reps
---------- A.J. GREENE
height | 6' 5"
weight | 298 lbs
---------- A.J. HAWK
height | 6' 1"
weight | 248 lbs
40 yard dash | 4.59s
vertical jump | 40"
broad jump | 115"
20 yard shuttle | 3.96s
bench press | 24 reps
---------- A.J. JEFFERSON
height | 6' 1"
weight | 193 lbs
arm length | 32½"
hand size | 9¼"
40 yard dash | 4.42s
vertical jump | 44"
broad jump | 126"
20 yard shuttle | 4s
bench press | 7 reps
---------- A.J. JENKINS
height | 6' 0"
weight | 190 lbs
arm length | 32¾"
hand size | 9½"
40 yard dash | 4.39s
vertical jump | 38"
broad jump | 124"
3-cone drill | 6.73s*
20 yard shuttle | 4.12s*
bench press | 12 reps
---------- A.J. KLEIN
height | 6' 1"
weight | 250 lbs
arm length | 32⅞"
hand size | 10¼"
10 yard split | 1.6s
40 yard dash | 4.66s
broad jump | 113"
bench press | 20 reps
---------- A.J. MCCARRON
height | 6' 3¼"
weight | 220 lbs
arm length | 31½"
hand size | 10"
10 yard split | 1.75s
40 yard dash | 4.94s
vertical jump | 28"
broad jump | 99"
3-cone drill | 7.18s
20 yard shuttle | 4.34s
---------- A.J. NICHOLSON
height | 6' 1"
weight | 252 lbs
40 yard dash | 4.88s
broad jump | 116"
20 yard shuttle | 4.46s
bench press | 25 reps
---------- A.J. STAMPS
height | 5' 11"
weight | 193 lbs
arm length | 31⅜"
hand size | 9⅝"
10 yard split | 1.77s
40 yard dash | 4.79s
vertical jump | 33"
broad jump | 115"
3-cone drill | 7.17s
20 yard shuttle | 4.25s
60 yard shuttle | 11.56s
bench press | 15 reps
---------- A.J. TERRELL
height | 6' 1"
weight | 195 lbs
arm length | 31¼"
hand size | 9"
40 yard dash | 4.42s
vertical jump | 34½"
broad jump | 129"
bench press | 15 reps
---------- A.Q. SHIPLEY
height | 6' 1"
weight | 304 lbs
40 yard dash | 5.19s
vertical jump | 31"
broad jump | 100"
20 yard shuttle | 4.4s
bench press | 33 reps
---------- AJ BARNER
height | 6' 6"
weight | 251 lbs
wingspan | 81⅞"
arm length | 33⅜"
hand size | 9"
---------- AJ HAULCY
height | 5' 11⅝"
weight | 215 lbs
arm length | 30⅞"
hand size | 9¼"
10 yard split | 1.62s
40 yard dash | 4.52s
---------- AT PERRY
height | 6' 3⅝"
weight | 198 lbs
arm length | 33¼"
hand size | 9¼"
10 yard split | 1.59s
40 yard dash | 4.47s
vertical jump | 35"
broad jump | 133"
---------- AAMIL WAGNER
height | 6' 6"
weight | 306 lbs
arm length | 34½"
hand size | 10¼"
10 yard split | 1.79s
40 yard dash | 5.01s
vertical jump | 29½"
broad jump | 108"
bench press | 21 reps
---------- AARON  LYNCH
height | 6' 5"
weight | 249 lbs
arm length | 34"
hand size | 10¼"
bench press | 18 reps
---------- AARON ANDERSON
height | 5' 8"
weight | 191 lbs
arm length | 29¾"
hand size | 9¼"
vertical jump | 30"
---------- AARON BANKS
height | 6' 5⅜"*
weight | 325 lbs*
wingspan | 80¾"*
arm length | 33⅛"*
hand size | 10⅛"*
10 yard split | 1.91s*
20 yard split | 3s*
40 yard dash | 5.34s*
vertical jump | 31"*
broad jump | 100"*
3-cone drill | 7.73s*
20 yard shuttle | 4.92s*
bench press | 24 reps*
---------- AARON BROOKS
height | 6' 4"
weight | 203 lbs
40 yard dash | 4.6s
vertical jump | 35½"
broad jump | 120"
20 yard shuttle | 4.29s
---------- AARON BURBRIDGE
height | 6' 0"
weight | 206 lbs
arm length | 31⅝"
hand size | 8¼"
10 yard split | 1.63s
40 yard dash | 4.56s
vertical jump | 30½"
broad jump | 115"
3-cone drill | 7.22s
20 yard shuttle | 4.31s
60 yard shuttle | 11.9s
bench press | 20 reps
---------- AARON CASEY
height | 6' 0⅞"
weight | 231 lbs
wingspan | 77⅞"
arm length | 32¾"
hand size | 10"
10 yard split | 1.59s
40 yard dash | 4.75s
vertical jump | 30"
broad jump | 117"
bench press | 16 reps
---------- AARON COLVIN
height | 5' 11"
weight | 177 lbs
arm length | 31"
hand size | 9¼"
---------- AARON CORP
height | 6' 4"
weight | 215 lbs
arm length | 32"
hand size | 9⅜"
40 yard dash | 4.72s
vertical jump | 31½"
broad jump | 106"
3-cone drill | 7.03s
20 yard shuttle | 4.3s
---------- AARON CURRY
height | 6' 2"
weight | 254 lbs
40 yard dash | 4.52s
vertical jump | 37"
broad jump | 124"
20 yard shuttle | 4.51s
bench press | 25 reps
---------- AARON DALAN
height | 6' 8"
weight | 328 lbs
40 yard dash | 5.24s
vertical jump | 23½"
broad jump | 99"
20 yard shuttle | 4.61s
bench press | 23 reps
---------- AARON DAVIS
height | 6' 0"
weight | 225 lbs
arm length | 31"
hand size | 9"
10 yard split | 1.75s
40 yard dash | 4.95s
vertical jump | 29"
broad jump | 107"
3-cone drill | 7.38s
20 yard shuttle | 4.37s
60 yard shuttle | 12.01s
bench press | 16 reps
---------- AARON DOBSON
height | 6' 2¾"*
weight | 210 lbs*
arm length | 33"
hand size | 9"
10 yard split | 1.51s*
20 yard split | 2.6s*
40 yard dash | 4.37s*
vertical jump | 35"*
broad jump | 121"*
3-cone drill | 7.19s*
20 yard shuttle | 4.33s*
bench press | 16 reps*
---------- AARON DONALD
height | 6' 1"
weight | 285 lbs
arm length | 32⅝"
hand size | 9⅞"
10 yard split | 1.59s
40 yard dash | 4.68s
vertical jump | 32"
broad jump | 116"
3-cone drill | 7.11s
20 yard shuttle | 4.39s
bench press | 35 reps
---------- AARON FAIROOZ
height | 6' 6"
weight | 209 lbs
40 yard dash | 4.49s
vertical jump | 36"
broad jump | 125"
20 yard shuttle | 4.27s
---------- AARON FIELDS
height | 6' 4"
weight | 243 lbs
40 yard dash | 4.76s
vertical jump | 34"
broad jump | 115"
20 yard shuttle | 4.56s
bench press | 22 reps
---------- AARON FRANCISCO
height | 6' 2"
weight | 211 lbs
40 yard dash | 4.74s
vertical jump | 35"
broad jump | 113"
20 yard shuttle | 4.13s
bench press | 17 reps
---------- AARON FULLER
height | 5' 11"
weight | 188 lbs
arm length | 29¾"
hand size | 8⅞"
40 yard dash | 4.59s
vertical jump | 34"
broad jump | 118"
3-cone drill | 7.14s
---------- AARON GIBSON
height | 6' 6"
weight | 386 lbs
40 yard dash | 5.35s
vertical jump | 24"
broad jump | 111"
20 yard shuttle | 4.54s
bench press | 31 reps
---------- AARON HANSFORD
height | 6' 2¼"
weight | 239 lbs
wingspan | 78½"
arm length | 32⅜"
hand size | 10⅛"
bench press | 24 reps
---------- AARON HESTER
height | 6' 2"
weight | 198 lbs
arm length | 32½"
hand size | 10⅜"
10 yard split | 1.59s
40 yard dash | 4.62s
vertical jump | 29"
broad jump | 112"
3-cone drill | 7.26s
20 yard shuttle | 4.33s
---------- AARON HUMPHREY
height | 6' 3"
weight | 254 lbs
40 yard dash | 5.1s
vertical jump | 34"
broad jump | 119"
bench press | 21 reps
---------- AARON HUNT
height | 6' 3"
weight | 262 lbs
40 yard dash | 4.86s
vertical jump | 30"
broad jump | 106"
20 yard shuttle | 4.52s
bench press | 24 reps
---------- AARON JONES
height | 5' 9"
weight | 208 lbs
arm length | 32½"
hand size | 9½"
40 yard dash | 4.56s
vertical jump | 37½"
broad jump | 127"
3-cone drill | 6.82s
20 yard shuttle | 4.2s
60 yard shuttle | 11.53s
bench press | 16 reps
---------- AARON KELLY
height | 6' 5"
weight | 204 lbs
arm length | 32¾"
hand size | 9½"
40 yard dash | 4.49s
vertical jump | 38"
broad jump | 119"
3-cone drill | 7.25s
20 yard shuttle | 4.45s
bench press | 11 reps
---------- AARON LOCKETT
height | 5' 8"
weight | 155 lbs
40 yard dash | 4.31s
vertical jump | 35"
broad jump | 119"
20 yard shuttle | 4.11s
---------- AARON MAYBIN
height | 6' 4"
weight | 249 lbs
40 yard dash | 4.78s
vertical jump | 38"
broad jump | 124"
3-cone drill | 7.52s
20 yard shuttle | 4.38s
bench press | 22 reps
---------- AARON MELLETTE
height | 6' 2"
weight | 217 lbs
arm length | 33⅛"
hand size | 9⅝"
10 yard split | 1.56s
40 yard dash | 4.54s
vertical jump | 33½"
broad jump | 123"
3-cone drill | 7.11s
20 yard shuttle | 4.41s
bench press | 9 reps
---------- AARON MURRAY
height | 6' 0"
weight | 207 lbs
arm length | 30⅝"
hand size | 9⅛"
---------- AARON PARKER
height | 6' 2"
weight | 209 lbs
arm length | 31⅛"
hand size | 9⅛"
40 yard dash | 4.57s
vertical jump | 26½"
broad jump | 112"
3-cone drill | 6.94s
20 yard shuttle | 4.23s
bench press | 12 reps
---------- AARON ROBINSON
height | 5' 11½"*
weight | 186 lbs*
wingspan | 72½"*
arm length | 30¼"*
hand size | 8¾"*
10 yard split | 1.58s*
20 yard split | 2.46s*
40 yard dash | 4.39s*
vertical jump | 37"*
broad jump | 123"*
3-cone drill | 6.9s*
20 yard shuttle | 4.31s*
bench press | 15 reps*
---------- AARON RODGERS
height | 6' 2"
weight | 223 lbs
hand size | 9⅜"
40 yard dash | 4.71s
vertical jump | 34½"
broad jump | 110"
3-cone drill | 7.39s
20 yard shuttle | 4.32s*
---------- AARON ROSS
height | 6' 1"
weight | 193 lbs
40 yard dash | 4.44s
vertical jump | 34"
broad jump | 118"
20 yard shuttle | 4.15s
bench press | 17 reps
---------- AARON ROUSE
height | 6' 4"
weight | 223 lbs
40 yard dash | 4.58s
vertical jump | 35"
bench press | 16 reps
---------- AARON SCHOBEL
height | 6' 4"
weight | 263 lbs
40 yard dash | 4.75s*
vertical jump | 38"
broad jump | 119"
20 yard shuttle | 4.03s
---------- AARON SHEA
height | 6' 4"
weight | 253 lbs
40 yard dash | 4.81s
vertical jump | 37½"
broad jump | 114"
20 yard shuttle | 4.3s
---------- AARON SMITH
height | 6' 5"
weight | 279 lbs
40 yard dash | 5.06s
vertical jump | 29½"
broad jump | 110"
20 yard shuttle | 4.34s
bench press | 19 reps
---------- AARON STECKER
height | 5' 10"
weight | 210 lbs
40 yard dash | 4.84s
vertical jump | 32½"
broad jump | 113"
20 yard shuttle | 4.17s
bench press | 23 reps
---------- AARON WALKER
height | 6' 6"
weight | 252 lbs
40 yard dash | 4.72s
vertical jump | 33½"
broad jump | 115"
20 yard shuttle | 4.3s
bench press | 24 reps
---------- AARON WILLIAMS
height | 6' 1"
weight | 204 lbs
arm length | 31½"
hand size | 9¼"
40 yard dash | 4.55s
vertical jump | 37½"
broad jump | 127"
20 yard shuttle | 4.07s
bench press | 18 reps
---------- AARON WILLIAMS
height | 6' 5"
weight | 253 lbs
40 yard dash | 4.79s
vertical jump | 33½"
broad jump | 108"
20 yard shuttle | 4.34s
bench press | 19 reps
---------- ABDUAL HOWARD
height | 6' 1"
weight | 209 lbs
40 yard dash | 4.64s
broad jump | 120"
---------- ABDUL CARTER
---------- ABDUL HODGE
height | 6' 1"
weight | 236 lbs
40 yard dash | 4.76s
vertical jump | 31"
broad jump | 108"
20 yard shuttle | 4.35s
---------- ABRAHAM ELIMIMIAN
height | 5' 10"
weight | 190 lbs
40 yard dash | 4.62s
vertical jump | 39"
broad jump | 121"
20 yard shuttle | 4.05s
bench press | 14 reps
---------- ABRAHAM LUCAS
height | 6' 6⅜"
weight | 315 lbs
wingspan | 81¾"
arm length | 33⅞"
hand size | 10½"
10 yard split | 1.76s
40 yard dash | 4.92s
vertical jump | 27"
broad jump | 107"
3-cone drill | 7.25s
20 yard shuttle | 4.4s
bench press | 24 reps
---------- ABRAHAM WRIGHT
height | 6' 2"
weight | 242 lbs
40 yard dash | 4.9s
vertical jump | 31"
broad jump | 111"
20 yard shuttle | 4.46s
bench press | 24 reps
---------- ABRAM SMITH
height | 6' 0"
weight | 213 lbs
wingspan | 72⅜"
arm length | 30¼"
hand size | 8¼"
---------- ABRY JONES
height | 6' 3"
weight | 313 lbs
arm length | 35"
hand size | 9¾"
vertical jump | 26½"
broad jump | 101"
bench press | 30 reps
---------- ACE SANDERS
height | 5' 7"
weight | 173 lbs
arm length | 29½"
hand size | 8⅞"
10 yard split | 1.55s
40 yard dash | 4.58s
vertical jump | 32"
broad jump | 117"
3-cone drill | 6.81s
20 yard shuttle | 4.37s
60 yard shuttle | 11.29s
bench press | 7 reps
---------- ADALIUS THOMAS
height | 6' 3"
weight | 270 lbs
40 yard dash | 4.56s
vertical jump | 38½"
broad jump | 120"
20 yard shuttle | 4.42s
---------- ADAM ARCHULETA
height | 6' 1"
weight | 211 lbs
40 yard dash | 4.46s*
bench press | 31 reps
---------- ADAM BERGEN
height | 6' 5"
weight | 259 lbs
40 yard dash | 4.78s
vertical jump | 38"
broad jump | 121"
20 yard shuttle | 4.11s
bench press | 25 reps
---------- ADAM BISHOP
height | 6' 5"
weight | 248 lbs
40 yard dash | 4.98s
vertical jump | 27"
broad jump | 113"
20 yard shuttle | 4.28s
bench press | 21 reps
---------- ADAM BISNOWATY
height | 6' 6"
weight | 304 lbs
arm length | 33⅞"
hand size | 11⅜"
40 yard dash | 5.23s
vertical jump | 29½"
broad jump | 96"
3-cone drill | 8.02s
20 yard shuttle | 4.94s
bench press | 23 reps
---------- ADAM CARRIKER
height | 6' 6"
weight | 296 lbs
40 yard dash | 4.9s
vertical jump | 33½"
broad jump | 110"
20 yard shuttle | 4.18s
bench press | 33 reps
---------- ADAM DAVIS
height | 6' 4"
weight | 309 lbs
40 yard dash | 5.66s
vertical jump | 26"
broad jump | 92"
20 yard shuttle | 5s
---------- ADAM GETTIS
height | 6' 2"
weight | 293 lbs
arm length | 33⅛"
hand size | 9½"
40 yard dash | 5s
vertical jump | 31"
broad jump | 112"
3-cone drill | 7.99s
20 yard shuttle | 4.65s
---------- ADAM GOTSIS
height | 6' 4"
weight | 287 lbs
arm length | 34⅛"
hand size | 10¾"
---------- ADAM GRANT
height | 6' 6"
weight | 325 lbs
arm length | 34"
hand size | 10½"
40 yard dash | 5.54s
vertical jump | 26½"
broad jump | 99"
20 yard shuttle | 5s
bench press | 25 reps
---------- ADAM HAAYER
height | 6' 6"
weight | 298 lbs
40 yard dash | 5.3s*
bench press | 23 reps
---------- ADAM JENNINGS
height | 5' 9"
weight | 181 lbs
40 yard dash | 4.44s
vertical jump | 37½"
broad jump | 118"
20 yard shuttle | 4.16s
---------- ADAM KIEFT
height | 6' 7"
weight | 337 lbs
40 yard dash | 5.52s
vertical jump | 33"
broad jump | 110"
20 yard shuttle | 4.77s
bench press | 28 reps
---------- ADAM KOETS
height | 6' 5"
weight | 298 lbs
40 yard dash | 5.08s
vertical jump | 32"
broad jump | 106"
20 yard shuttle | 4.47s
bench press | 20 reps
---------- ADAM KORSAK
height | 6' 1"
weight | 187 lbs
arm length | 29⅜"
hand size | 8¾"
---------- ADAM MUEMA
height | 5' 10"
weight | 202 lbs
arm length | 29⅞"
hand size | 9¾"
---------- ADAM RANDALL
height | 6' 3"
weight | 232 lbs
arm length | 32⅜"
hand size | 9¾"
10 yard split | 1.6s
40 yard dash | 4.5s
vertical jump | 37"
broad jump | 124"
20 yard shuttle | 4.53s
bench press | 26 reps
---------- ADAM SEWARD
height | 6' 2"
weight | 248 lbs
40 yard dash | 4.6s
vertical jump | 36½"
broad jump | 120"
20 yard shuttle | 4.11s
bench press | 33 reps
---------- ADAM SHAHEEN
height | 6' 6"
weight | 278 lbs
arm length | 33½"
hand size | 9⅝"
40 yard dash | 4.79s
vertical jump | 32½"
broad jump | 121"
3-cone drill | 7.09s
20 yard shuttle | 4.38s
60 yard shuttle | 12.38s
bench press | 24 reps
---------- ADAM SHEAD
height | 6' 4"
weight | 338 lbs
arm length | 33¾"
hand size | 10⅜"
10 yard split | 1.96s
40 yard dash | 5.74s
bench press | 26 reps
---------- ADAM SNYDER
height | 6' 6"
weight | 316 lbs
40 yard dash | 5.34s
vertical jump | 28½"
broad jump | 93"
20 yard shuttle | 4.86s
bench press | 21 reps
---------- ADAM TAFRALIS
height | 6' 1"
weight | 221 lbs
40 yard dash | 4.78s
vertical jump | 32"
broad jump | 108"
20 yard shuttle | 4.33s
---------- ADAM TERRY
height | 6' 8"
weight | 330 lbs
40 yard dash | 5.4s
vertical jump | 28"
broad jump | 96"
20 yard shuttle | 4.79s
---------- ADAM THIELEN
height | 6' 1⅛"*
weight | 192 lbs*
20 yard split | 2.54s*
40 yard dash | 4.49s*
vertical jump | 36"*
broad jump | 120"*
3-cone drill | 6.77s*
20 yard shuttle | 4.49s*
---------- ADAM TRAUTMAN
height | 6' 5"
weight | 255 lbs
arm length | 32⅝"
hand size | 9½"
40 yard dash | 4.8s
vertical jump | 34½"
broad jump | 114"
3-cone drill | 6.78s
20 yard shuttle | 4.27s
bench press | 18 reps
---------- ADAM ULATOSKI
height | 6' 6"
weight | 300 lbs
arm length | 33¼"
hand size | 9⅝"
40 yard dash | 5.52s
vertical jump | 26"
20 yard shuttle | 4.99s
bench press | 24 reps
---------- ADARIUS BOWMAN
height | 6' 3"
weight | 223 lbs
40 yard dash | 4.74s
bench press | 14 reps
---------- ADE ARUNA
height | 6' 4⅝"
weight | 262 lbs
wingspan | 80"
arm length | 34"
hand size | 10⅝"
40 yard dash | 4.6s
vertical jump | 38½"
broad jump | 128"
3-cone drill | 7.53s
20 yard shuttle | 4.48s
bench press | 18 reps
---------- ADELL DUCKETT
height | 6' 4"
weight | 270 lbs
40 yard dash | 4.93s
vertical jump | 34½"
broad jump | 105"
20 yard shuttle | 4.35s
bench press | 14 reps
---------- ADETOKUNBO OGUNDEJI
height | 6' 4½"*
weight | 260 lbs*
wingspan | 84"*
arm length | 35¼"*
hand size | 9⅝"*
10 yard split | 1.71s*
20 yard split | 2.76s*
40 yard dash | 4.8s*
vertical jump | 32"*
broad jump | 120"*
3-cone drill | 7.19s*
20 yard shuttle | 4.65s*
bench press | 22 reps*
---------- ADETOMIWA ADEBAWORE
height | 6' 1⅝"
weight | 282 lbs
arm length | 33⅞"
hand size | 10½"
10 yard split | 1.61s
40 yard dash | 4.49s
vertical jump | 37½"
broad jump | 125"
bench press | 27 reps
---------- ADISA ISAAC
height | 6' 4⅜"
weight | 247 lbs
wingspan | 81"
arm length | 33⅞"
hand size | 10"
10 yard split | 1.64s
40 yard dash | 4.74s
vertical jump | 34½"
broad jump | 123"
---------- ADOLPHUS WASHINGTON
height | 6' 3"
weight | 301 lbs
arm length | 34½"
hand size | 9⅞"
10 yard split | 1.79s
40 yard dash | 5.17s
vertical jump | 27"
broad jump | 99"
3-cone drill | 8.06s
20 yard shuttle | 4.79s
bench press | 21 reps
---------- ADONAI MITCHELL
height | 6' 2¼"
weight | 205 lbs
wingspan | 77⅝"
arm length | 32⅜"
hand size | 9"
10 yard split | 1.52s
40 yard dash | 4.34s
vertical jump | 39½"
broad jump | 136"
---------- ADOREE' JACKSON
height | 5' 10"
weight | 186 lbs
arm length | 31⅜"
hand size | 9¼"
40 yard dash | 4.42s
vertical jump | 36"
broad jump | 122"
---------- ADRIAN AMOS
height | 6' 0"
weight | 218 lbs
arm length | 32¼"
hand size | 9⅛"
10 yard split | 1.5s
40 yard dash | 4.56s
vertical jump | 35½"
broad jump | 122"
3-cone drill | 7.09s
20 yard shuttle | 4.03s
60 yard shuttle | 11.33s
---------- ADRIAN AWASOM
height | 6' 4"
weight | 279 lbs
40 yard dash | 4.93s
vertical jump | 32½"
broad jump | 107"
20 yard shuttle | 4.4s
bench press | 23 reps
---------- ADRIAN BUSHELL
height | 5' 9"
weight | 186 lbs
arm length | 32"
hand size | 9¼"
10 yard split | 1.55s
40 yard dash | 4.58s
vertical jump | 33"
broad jump | 116"
3-cone drill | 6.92s
20 yard shuttle | 4.25s
bench press | 17 reps
---------- ADRIAN CLAYBORN
height | 6' 3"
weight | 281 lbs
arm length | 32½"
hand size | 9¾"
40 yard dash | 4.78s
vertical jump | 33"
broad jump | 113"
3-cone drill | 7.3s
20 yard shuttle | 4.13s
---------- ADRIAN DINGLE
height | 6' 3"
weight | 290 lbs
40 yard dash | 4.94s
vertical jump | 33"
broad jump | 112"
20 yard shuttle | 4.4s
bench press | 20 reps
---------- ADRIAN EALY
height | 6' 6¼"*
weight | 321 lbs*
wingspan | 80⅞"*
arm length | 33"*
hand size | 10"*
10 yard split | 1.84s*
20 yard split | 3.1s*
40 yard dash | 5.42s*
vertical jump | 24½"*
broad jump | 104"*
3-cone drill | 8.82s*
20 yard shuttle | 4.87s*
bench press | 18 reps*
---------- ADRIAN GRADY
height | 6' 2"
weight | 298 lbs
40 yard dash | 5.19s
vertical jump | 32"
broad jump | 105"
20 yard shuttle | 4.72s
bench press | 31 reps
---------- ADRIAN HARDY
height | 6' 1"*
weight | 205 lbs*
wingspan | 77"*
arm length | 32"*
hand size | 9⅜"*
10 yard split | 1.61s*
20 yard split | 2.65s*
40 yard dash | 4.61s*

In [9]:
display(player_info_dict)

{'ashawnrobinson2016': {'player_name': "A'Shawn Robinson",
  'player_id': 'ashawnrobinson2016',
  'player_url': 'https://www.mockdraftable.com//player/ashawn-robinson?position=ATH',
  'draft_class': 2016,
  'position': 'Defensive Tackle',
  'college': 'Alabama',
  'height': '6\' 4"',
  'weight': '307 lbs',
  'arm length': '34½"',
  'hand size': '10½"',
  '10 yard split': '1.78s',
  '40 yard dash': '5.2s',
  'vertical jump': '26"',
  'broad jump': '106"',
  '3-cone drill': '7.8s',
  '20 yard shuttle': '4.74s',
  'bench press': '22 reps'},
 'acleonard2014': {'player_name': 'A.C. Leonard',
  'player_id': 'acleonard2014',
  'player_url': 'https://www.mockdraftable.com//player/ac-leonard?position=ATH',
  'draft_class': 2014,
  'position': 'Tight End',
  'college': 'Tennessee State',
  'height': '6\' 2"',
  'weight': '252 lbs',
  'arm length': '33"',
  'hand size': '9¼"',
  '40 yard dash': '4.5s',
  'vertical jump': '34"',
  'broad jump': '128"',
  'bench press': '20 reps'},
 'ajbrown2019': {'player_name': 'A.J. Brown',
  'player_id': 'ajbrown2019',
  'player_url': 'https://www.mockdraftable.com//player/aj-brown?position=ATH',
  'draft_class': 2019,
  'position': 'Wide Receiver',
  'college': 'Ole Miss',
  'height': '6\' 0½"',
  'weight': '226 lbs',
  'wingspan': '78"',
  'arm length': '32⅞"',
  'hand size': '9¾"',
  '40 yard dash': '4.49s',
  'vertical jump': '36½"',
  'broad jump': '120"',
  'bench press': '19 reps'},
 'ajcann2015': {'player_name': 'A.J. Cann',
  'player_id': 'ajcann2015',
  'player_url': 'https://www.mockdraftable.com//player/aj-cann?position=ATH',
  'draft_class': 2015,
  'position': 'Offensive Guard',
  'college': 'South Carolina',
  'height': '6\' 3"',
  'weight': '313 lbs',
  'arm length': '32⅝"',
  'hand size': '10¼"',
  'bench press': '26 reps'},
 'ajderby2015': {'player_name': 'A.J. Derby',
  'player_id': 'ajderby2015',
  'player_url': 'https://www.mockdraftable.com//player/aj-derby?position=ATH',
  'draft_class': 2015,
  'position': 'Tight End',
  'college': 'Arkansas',
  'height': '6\' 4"',
  'weight': '255 lbs',
  'arm length': '30½"',
  'hand size': '9½"',
  'bench press': '15 reps'},
 'ajedds2010': {'player_name': 'A.J. Edds',
  'player_id': 'ajedds2010',
  'player_url': 'https://www.mockdraftable.com//player/aj-edds?position=ATH',
  'draft_class': 2010,
  'position': 'Outside Linebacker',
  'college': 'Iowa',
  'height': '6\' 4"',
  'weight': '246 lbs',
  'arm length': '32¾"',
  'hand size': '9⅛"',
  '10 yard split': '1.6s',
  '40 yard dash': '4.62s',
  'vertical jump': '33"',
  'broad jump': '117"',
  '3-cone drill': '7.19s',
  '20 yard shuttle': '4.28s',
  'bench press': '16 reps'},
 'ajepenesa2020': {'player_name': 'A.J. Epenesa',
  'player_id': 'ajepenesa2020',
  'player_url': 'https://www.mockdraftable.com//player/aj-epenesa?position=ATH',
  'draft_class': 2020,
  'position': 'Defensive Line',
  'college': 'Iowa',
  'height': '6\' 5"',
  'weight': '275 lbs',
  'arm length': '34½"',
  'hand size': '10⅛"',
  '40 yard dash': '5.04s',
  'vertical jump': '32½"',
  'broad jump': '117"',
  '3-cone drill': '7.34s',
  '20 yard shuttle': '4.46s',
  'bench press': '17 reps'},
 'ajgreen2020': {'player_name': 'A.J. Green',
  'player_id': 'ajgreen2020',
  'player_url': 'https://www.mockdraftable.com//player/aj-green-2020?position=ATH',
  'draft_class': 2020,
  'position': 'Cornerback',
  'college': 'Oklahoma State',
  'height': '6\' 1"',
  'weight': '202 lbs',
  'arm length': '30⅞"',
  'hand size': '9"',
  '40 yard dash': '4.62s',
  'bench press': '13 reps'},
 'ajgreen2011': {'player_name': 'A.J. Green',
  'player_id': 'ajgreen2011',
  'player_url': 'https://www.mockdraftable.com//player/aj-green?position=ATH',
  'draft_class': 2011,
  'position': 'Wide Receiver',
  'college': 'Georgia',
  'height': '6\' 4"',
  'weight': '211 lbs',
  'arm length': '34⅜"',
  'hand size': '9¼"',
  '10 yard split': '1.55s',
  '20 yard split': '2.53s',
  '40 yard dash': '4.48s',
  'vertical jump': '34½"',
  'broad jump': '126"',
  '3-cone drill': '6.91s',
  '20 yard shuttle': '4.21s',
  '60 yard shuttle': '11.46s',
  'bench press': '18 reps'},
 'ajgreene2012': {'player_name': 'A.J. Greene',
  'player_id': 'ajgreene2012',
  'player_url': 'https://www.mockdraftable.com//player/aj-greene?position=ATH',
  'draft_class': 2012,
  'position': 'Offensive Tackle',
  'college': 'Auburn',
  'height': '6\' 5"',
  'weight': '298 lbs'},
 'ajhawk2006': {'player_name': 'A.J. Hawk',
  'player_id': 'ajhawk2006',
  'player_url': 'https://www.mockdraftable.com//player/aj-hawk?position=ATH',
  'draft_class': 2006,
  'position': 'Outside Linebacker',
  'college': 'Ohio State',
  'height': '6\' 1"',
  'weight': '248 lbs',
  '40 yard dash': '4.59s',
  'vertical jump': '40"',
  'broad jump': '115"',
  '20 yard shuttle': '3.96s',
  'bench press': '24 reps'},
 'ajjefferson2010': {'player_name': 'A.J. Jefferson',
  'player_id': 'ajjefferson2010',
  'player_url': 'https://www.mockdraftable.com//player/aj-jefferson?position=ATH',
  'draft_class': 2010,
  'position': 'Cornerback',
  'college': 'Fresno State',
  'height': '6\' 1"',
  'weight': '193 lbs',
  'arm length': '32½"',
  'hand size': '9¼"',
  '40 yard dash': '4.42s',
  'vertical jump': '44"',
  'broad jump': '126"',
  '20 yard shuttle': '4s',
  'bench press': '7 reps'},
 'ajjenkins2012': {'player_name': 'A.J. Jenkins',
  'player_id': 'ajjenkins2012',
  'player_url': 'https://www.mockdraftable.com//player/aj-jenkins?position=ATH',
  'draft_class': 2012,
  'position': 'Wide Receiver',
  'college': 'Illinois',
  'height': '6\' 0"',
  'weight': '190 lbs',
  'arm length': '32¾"',
  'hand size': '9½"',
  '40 yard dash': '4.39s',
  'vertical jump': '38"',
  'broad jump': '124"',
  '3-cone drill': '6.73s*',
  '20 yard shuttle': '4.12s*',
  'bench press': '12 reps'},
 'ajklein2013': {'player_name': 'A.J. Klein',
  'player_id': 'ajklein2013',
  'player_url': 'https://www.mockdraftable.com//player/aj-klein?position=ATH',
  'draft_class': 2013,
  'position': 'Inside Linebacker',
  'college': 'Iowa State',
  'height': '6\' 1"',
  'weight': '250 lbs',
  'arm length': '32⅞"',
  'hand size': '10¼"',
  '10 yard split': '1.6s',
  '40 yard dash': '4.66s',
  'broad jump': '113"',
  'bench press': '20 reps'},
 'ajmccarron2014': {'player_name': 'A.J. McCarron',
  'player_id': 'ajmccarron2014',
  'player_url': 'https://www.mockdraftable.com//player/aj-mccarron?position=ATH',
  'draft_class': 2014,
  'position': 'Quarterback',
  'college': 'Alabama',
  'height': '6\' 3¼"',
  'weight': '220 lbs',
  'arm length': '31½"',
  'hand size': '10"',
  '10 yard split': '1.75s',
  '40 yard dash': '4.94s',
  'vertical jump': '28"',
  'broad jump': '99"',
  '3-cone drill': '7.18s',
  '20 yard shuttle': '4.34s'},
 'ajnicholson2006': {'player_name': 'A.J. Nicholson',
  'player_id': 'ajnicholson2006',
  'player_url': 'https://www.mockdraftable.com//player/aj-nicholson?position=ATH',
  'draft_class': 2006,
  'position': 'Outside Linebacker',
  'college': 'Florida State',
  'height': '6\' 1"',
  'weight': '252 lbs',
  '40 yard dash': '4.88s',
  'broad jump': '116"',
  '20 yard shuttle': '4.46s',
  'bench press': '25 reps'},
 'ajstamps2016': {'player_name': 'A.J. Stamps',
  'player_id': 'ajstamps2016',
  'player_url': 'https://www.mockdraftable.com//player/aj-stamps?position=ATH',
  'draft_class': 2016,
  'position': 'Safety',
  'college': 'Kentucky',
  'height': '5\' 11"',
  'weight': '193 lbs',
  'arm length': '31⅜"',
  'hand size': '9⅝"',
  '10 yard split': '1.77s',
  '40 yard dash': '4.79s',
  'vertical jump': '33"',
  'broad jump': '115"',
  '3-cone drill': '7.17s',
  '20 yard shuttle': '4.25s',
  '60 yard shuttle': '11.56s',
  'bench press': '15 reps'},
 'ajterrell2020': {'player_name': 'A.J. Terrell',
  'player_id': 'ajterrell2020',
  'player_url': 'https://www.mockdraftable.com//player/aj-terrell?position=ATH',
  'draft_class': 2020,
  'position': 'Cornerback',
  'college': 'Clemson',
  'height': '6\' 1"',
  'weight': '195 lbs',
  'arm length': '31¼"',
  'hand size': '9"',
  '40 yard dash': '4.42s',
  'vertical jump': '34½"',
  'broad jump': '129"',
  'bench press': '15 reps'},
 'aqshipley2009': {'player_name': 'A.Q. Shipley',
  'player_id': 'aqshipley2009',
  'player_url': 'https://www.mockdraftable.com//player/aq-shipley?position=ATH',
  'draft_class': 2009,
  'position': 'Offensive Center',
  'college': 'Penn State',
  'height': '6\' 1"',
  'weight': '304 lbs',
  '40 yard dash': '5.19s',
  'vertical jump': '31"',
  'broad jump': '100"',
  '20 yard shuttle': '4.4s',
  'bench press': '33 reps'},
 'ajbarner2024': {'player_name': 'AJ Barner',
  'player_id': 'ajbarner2024',
  'player_url': 'https://www.mockdraftable.com//player/aj-barner?position=ATH',
  'draft_class': 2024,
  'position': 'Tight End',
  'college': 'Michigan',
  'height': '6\' 6"',
  'weight': '251 lbs',
  'wingspan': '81⅞"',
  'arm length': '33⅜"',
  'hand size': '9"'},
 'ajhaulcy2026': {'player_name': 'AJ Haulcy',
  'player_id': 'ajhaulcy2026',
  'player_url': 'https://www.mockdraftable.com//player/aj-haulcy?position=ATH',
  'draft_class': 2026,
  'position': 'Safety',
  'college': 'LSU',
  'height': '5\' 11⅝"',
  'weight': '215 lbs',
  'arm length': '30⅞"',
  'hand size': '9¼"',
  '10 yard split': '1.62s',
  '40 yard dash': '4.52s'},
 'atperry2023': {'player_name': 'AT Perry',
  'player_id': 'atperry2023',
  'player_url': 'https://www.mockdraftable.com//player/at-perry?position=ATH',
  'draft_class': 2023,
  'position': 'Wide Receiver',
  'college': 'Wake Forest',
  'height': '6\' 3⅝"',
  'weight': '198 lbs',
  'arm length': '33¼"',
  'hand size': '9¼"',
  '10 yard split': '1.59s',
  '40 yard dash': '4.47s',
  'vertical jump': '35"',
  'broad jump': '133"'},
 'aamilwagner2026': {'player_name': 'Aamil Wagner',
  'player_id': 'aamilwagner2026',
  'player_url': 'https://www.mockdraftable.com//player/aamil-wagner?position=ATH',
  'draft_class': 2026,
  'position': 'Offensive Tackle',
  'college': 'Notre Dame',
  'height': '6\' 6"',
  'weight': '306 lbs',
  'arm length': '34½"',
  'hand size': '10¼"',
  '10 yard split': '1.79s',
  '40 yard dash': '5.01s',
  'vertical jump': '29½"',
  'broad jump': '108"',
  'bench press': '21 reps'},
 'aaronlynch2014': {'player_name': 'Aaron  Lynch',
  'player_id': 'aaronlynch2014',
  'player_url': 'https://www.mockdraftable.com//player/aaron-lynch?position=ATH',
  'draft_class': 2014,
  'position': 'One-Gap Defensive End',
  'college': 'South Florida',
  'height': '6\' 5"',
  'weight': '249 lbs',
  'arm length': '34"',
  'hand size': '10¼"',
  'bench press': '18 reps'},
 'aaronanderson2026': {'player_name': 'Aaron Anderson',
  'player_id': 'aaronanderson2026',
  'player_url': 'https://www.mockdraftable.com//player/aaron-anderson?position=ATH',
  'draft_class': 2026,
  'position': 'Wide Receiver',
  'college': 'LSU',
  'height': '5\' 8"',
  'weight': '191 lbs',
  'arm length': '29¾"',
  'hand size': '9¼"',
  'vertical jump': '30"'},
 'aaronbanks2021': {'player_name': 'Aaron Banks',
  'player_id': 'aaronbanks2021',
  'player_url': 'https://www.mockdraftable.com//player/aaron-banks?position=ATH',
  'draft_class': 2021,
  'position': 'Offensive Guard',
  'college': 'Notre Dame',
  'height': '6\' 5⅜"*',
  'weight': '325 lbs*',
  'wingspan': '80¾"*',
  'arm length': '33⅛"*',
  'hand size': '10⅛"*',
  '10 yard split': '1.91s*',
  '20 yard split': '3s*',
  '40 yard dash': '5.34s*',
  'vertical jump': '31"*',
  'broad jump': '100"*',
  '3-cone drill': '7.73s*',
  '20 yard shuttle': '4.92s*',
  'bench press': '24 reps*'},
 'aaronbrooks1999': {'player_name': 'Aaron Brooks',
  'player_id': 'aaronbrooks1999',
  'player_url': 'https://www.mockdraftable.com//player/aaron-brooks?position=ATH',
  'draft_class': 1999,
  'position': 'Quarterback',
  'college': 'Virginia',
  'height': '6\' 4"',
  'weight': '203 lbs',
  '40 yard dash': '4.6s',
  'vertical jump': '35½"',
  'broad jump': '120"',
  '20 yard shuttle': '4.29s'},
 'aaronburbridge2016': {'player_name': 'Aaron Burbridge',
  'player_id': 'aaronburbridge2016',
  'player_url': 'https://www.mockdraftable.com//player/aaron-burbridge?position=ATH',
  'draft_class': 2016,
  'position': 'Wide Receiver',
  'college': 'Michigan State',
  'height': '6\' 0"',
  'weight': '206 lbs',
  'arm length': '31⅝"',
  'hand size': '8¼"',
  '10 yard split': '1.63s',
  '40 yard dash': '4.56s',
  'vertical jump': '30½"',
  'broad jump': '115"',
  '3-cone drill': '7.22s',
  '20 yard shuttle': '4.31s',
  '60 yard shuttle': '11.9s',
  'bench press': '20 reps'},
 'aaroncasey2024': {'player_name': 'Aaron Casey',
  'player_id': 'aaroncasey2024',
  'player_url': 'https://www.mockdraftable.com//player/aaron-casey?position=ATH',
  'draft_class': 2024,
  'position': 'Linebacker',
  'college': 'Indiana',
  'height': '6\' 0⅞"',
  'weight': '231 lbs',
  'wingspan': '77⅞"',
  'arm length': '32¾"',
  'hand size': '10"',
  '10 yard split': '1.59s',
  '40 yard dash': '4.75s',
  'vertical jump': '30"',
  'broad jump': '117"',
  'bench press': '16 reps'},
 'aaroncolvin2014': {'player_name': 'Aaron Colvin',
  'player_id': 'aaroncolvin2014',
  'player_url': 'https://www.mockdraftable.com//player/aaron-colvin?position=ATH',
  'draft_class': 2014,
  'position': 'Cornerback',
  'college': 'Oklahoma',
  'height': '5\' 11"',
  'weight': '177 lbs',
  'arm length': '31"',
  'hand size': '9¼"'},
 'aaroncorp2012': {'player_name': 'Aaron Corp',
  'player_id': 'aaroncorp2012',
  'player_url': 'https://www.mockdraftable.com//player/aaron-corp?position=ATH',
  'draft_class': 2012,
  'position': 'Quarterback',
  'college': 'Richmond',
  'height': '6\' 4"',
  'weight': '215 lbs',
  'arm length': '32"',
  'hand size': '9⅜"',
  '40 yard dash': '4.72s',
  'vertical jump': '31½"',
  'broad jump': '106"',
  '3-cone drill': '7.03s',
  '20 yard shuttle': '4.3s'},
 'aaroncurry2009': {'player_name': 'Aaron Curry',
  'player_id': 'aaroncurry2009',
  'player_url': 'https://www.mockdraftable.com//player/aaron-curry?position=ATH',
  'draft_class': 2009,
  'position': 'Outside Linebacker',
  'college': 'Wake Forest',
  'height': '6\' 2"',
  'weight': '254 lbs',
  '40 yard dash': '4.52s',
  'vertical jump': '37"',
  'broad jump': '124"',
  '20 yard shuttle': '4.51s',
  'bench press': '25 reps'},
 'aarondalan1999': {'player_name': 'Aaron Dalan',
  'player_id': 'aarondalan1999',
  'player_url': 'https://www.mockdraftable.com//player/aaron-dalan?position=ATH',
  'draft_class': 1999,
  'position': 'Offensive Tackle',
  'college': 'Washington',
  'height': '6\' 8"',
  'weight': '328 lbs',
  '40 yard dash': '5.24s',
  'vertical jump': '23½"',
  'broad jump': '99"',
  '20 yard shuttle': '4.61s',
  'bench press': '23 reps'},
 'aarondavis2015': {'player_name': 'Aaron Davis',
  'player_id': 'aarondavis2015',
  'player_url': 'https://www.mockdraftable.com//player/aaron-davis?position=ATH',
  'draft_class': 2015,
  'position': 'Outside Linebacker',
  'college': 'Colorado State',
  'height': '6\' 0"',
  'weight': '225 lbs',
  'arm length': '31"',
  'hand size': '9"',
  '10 yard split': '1.75s',
  '40 yard dash': '4.95s',
  'vertical jump': '29"',
  'broad jump': '107"',
  '3-cone drill': '7.38s',
  '20 yard shuttle': '4.37s',
  '60 yard shuttle': '12.01s',
  'bench press': '16 reps'},
 'aarondobson2013': {'player_name': 'Aaron Dobson',
  'player_id': 'aarondobson2013',
  'player_url': 'https://www.mockdraftable.com//player/aaron-dobson?position=ATH',
  'draft_class': 2013,
  'position': 'Wide Receiver',
  'college': 'Marshall',
  'height': '6\' 2¾"*',
  'weight': '210 lbs*',
  'arm length': '33"',
  'hand size': '9"',
  '10 yard split': '1.51s*',
  '20 yard split': '2.6s*',
  '40 yard dash': '4.37s*',
  'vertical jump': '35"*',
  'broad jump': '121"*',
  '3-cone drill': '7.19s*',
  '20 yard shuttle': '4.33s*',
  'bench press': '16 reps*'},
 'aarondonald2014': {'player_name': 'Aaron Donald',
  'player_id': 'aarondonald2014',
  'player_url': 'https://www.mockdraftable.com//player/aaron-donald?position=ATH',
  'draft_class': 2014,
  'position': 'Defensive Tackle',
  'college': 'Pittsburgh',
  'height': '6\' 1"',
  'weight': '285 lbs',
  'arm length': '32⅝"',
  'hand size': '9⅞"',
  '10 yard split': '1.59s',
  '40 yard dash': '4.68s',
  'vertical jump': '32"',
  'broad jump': '116"',
  '3-cone drill': '7.11s',
  '20 yard shuttle': '4.39s',
  'bench press': '35 reps'},
 'aaronfairooz2007': {'player_name': 'Aaron Fairooz',
  'player_id': 'aaronfairooz2007',
  'player_url': 'https://www.mockdraftable.com//player/aaron-fairooz?position=ATH',
  'draft_class': 2007,
  'position': 'Wide Receiver',
  'college': 'Central Arkansas',
  'height': '6\' 6"',
  'weight': '209 lbs',
  '40 yard dash': '4.49s',
  'vertical jump': '36"',
  'broad jump': '125"',
  '20 yard shuttle': '4.27s'},
 'aaronfields2000': {'player_name': 'Aaron Fields',
  'player_id': 'aaronfields2000',
  'player_url': 'https://www.mockdraftable.com//player/aaron-fields?position=ATH',
  'draft_class': 2000,
  'position': 'One-Gap Defensive End',
  'college': 'Troy',
  'height': '6\' 4"',
  'weight': '243 lbs',
  '40 yard dash': '4.76s',
  'vertical jump': '34"',
  'broad jump': '115"',
  '20 yard shuttle': '4.56s',
  'bench press': '22 reps'},
 'aaronfrancisco2005': {'player_name': 'Aaron Francisco',
  'player_id': 'aaronfrancisco2005',
  'player_url': 'https://www.mockdraftable.com//player/aaron-francisco?position=ATH',
  'draft_class': 2005,
  'position': 'Safety',
  'college': 'BYU',
  'height': '6\' 2"',
  'weight': '211 lbs',
  '40 yard dash': '4.74s',
  'vertical jump': '35"',
  'broad jump': '113"',
  '20 yard shuttle': '4.13s',
  'bench press': '17 reps'},
 'aaronfuller2020': {'player_name': 'Aaron Fuller',
  'player_id': 'aaronfuller2020',
  'player_url': 'https://www.mockdraftable.com//player/aaron-fuller?position=ATH',
  'draft_class': 2020,
  'position': 'Wide Receiver',
  'college': 'Washington',
  'height': '5\' 11"',
  'weight': '188 lbs',
  'arm length': '29¾"',
  'hand size': '8⅞"',
  '40 yard dash': '4.59s',
  'vertical jump': '34"',
  'broad jump': '118"',
  '3-cone drill': '7.14s'},
 'aarongibson1999': {'player_name': 'Aaron Gibson',
  'player_id': 'aarongibson1999',
  'player_url': 'https://www.mockdraftable.com//player/aaron-gibson?position=ATH',
  'draft_class': 1999,
  'position': 'Offensive Tackle',
  'college': 'Wisconsin',
  'height': '6\' 6"',
  'weight': '386 lbs',
  '40 yard dash': '5.35s',
  'vertical jump': '24"',
  'broad jump': '111"',
  '20 yard shuttle': '4.54s',
  'bench press': '31 reps'},
 'aaronhansford2022': {'player_name': 'Aaron Hansford',
  'player_id': 'aaronhansford2022',
  'player_url': 'https://www.mockdraftable.com//player/aaron-hansford?position=ATH',
  'draft_class': 2022,
  'position': 'Linebacker',
  'college': 'Texas A&M',
  'height': '6\' 2¼"',
  'weight': '239 lbs',
  'wingspan': '78½"',
  'arm length': '32⅜"',
  'hand size': '10⅛"',
  'bench press': '24 reps'},
 'aaronhester2013': {'player_name': 'Aaron Hester',
  'player_id': 'aaronhester2013',
  'player_url': 'https://www.mockdraftable.com//player/aaron-hester?position=ATH',
  'draft_class': 2013,
  'position': 'Cornerback',
  'college': 'UCLA',
  'height': '6\' 2"',
  'weight': '198 lbs',
  'arm length': '32½"',
  'hand size': '10⅜"',
  '10 yard split': '1.59s',
  '40 yard dash': '4.62s',
  'vertical jump': '29"',
  'broad jump': '112"',
  '3-cone drill': '7.26s',
  '20 yard shuttle': '4.33s'},
 'aaronhumphrey2000': {'player_name': 'Aaron Humphrey',
  'player_id': 'aaronhumphrey2000',
  'player_url': 'https://www.mockdraftable.com//player/aaron-humphrey?position=ATH',
  'draft_class': 2000,
  'position': 'One-Gap Defensive End',
  'college': 'Texas',
  'height': '6\' 3"',
  'weight': '254 lbs',
  '40 yard dash': '5.1s',
  'vertical jump': '34"',
  'broad jump': '119"',
  'bench press': '21 reps'},
 'aaronhunt2003': {'player_name': 'Aaron Hunt',
  'player_id': 'aaronhunt2003',
  'player_url': 'https://www.mockdraftable.com//player/aaron-hunt?position=ATH',
  'draft_class': 2003,
  'position': 'One-Gap Defensive End',

In [10]:
nfl_combine_df = pd.DataFrame(player_info_dict.values())

nfl_combine_df_rename_cols = {
    'player_name':'md_player_name',
    'player_id':'md_player_id',
    'player_url':'md_url',
    'draft_class':'md_draft_class',
    'position':'md_position',
    'college':'md_college',
    'height':'md_height',
    'weight':'md_weight',
    'arm length':'md_arm_length',
    'hand size':'md_hand_size',
    'wingspan':'md_wing_span',
    '10 yard split':'md_yard_10_split',
    '20 yard split': 'md_yard_20_split',
    '40 yard dash':'md_yard_40_dash',
    'vertical jump': 'md_vert_jump',
    'broad jump':'md_broad_jump',
    '3-cone drill':'md_cone_drill',
    '20 yard shuttle':'md_yard_20_shuttle',
    '60 yard shuttle':'md_yard_60_shuttle',
    'bench press':'md_bench_press'
}

nfl_combine_df = nfl_combine_df.rename(columns=nfl_combine_df_rename_cols)

In [11]:
display(nfl_combine_df.head())

for c in nfl_combine_df.columns:
    print(c)

,md_player_name,md_player_id,md_url,md_draft_class,md_position,md_college,md_height,md_weight,md_arm_length,md_hand_size,md_yard_10_split,md_yard_40_dash,md_vert_jump,md_broad_jump,md_cone_drill,md_yard_20_shuttle,md_bench_press,md_wing_span,md_yard_20_split,md_yard_60_shuttle
0,A'Shawn Robinson,ashawnrobinson2016,https://www.mockdraftable.com//player/ashawn-r...,2016,Defensive Tackle,Alabama,"6' 4""",307 lbs,"34½""","10½""",1.78s,5.2s,"26""","106""",7.8s,4.74s,22 reps,NaN,NaN,NaN
1,A.C. Leonard,acleonard2014,https://www.mockdraftable.com//player/ac-leona...,2014,Tight End,Tennessee State,"6' 2""",252 lbs,"33""","9¼""",NaN,4.5s,"34""","128""",NaN,NaN,20 reps,NaN,NaN,NaN
2,A.J. Brown,ajbrown2019,https://www.mockdraftable.com//player/aj-brown...,2019,Wide Receiver,Ole Miss,"6' 0½""",226 lbs,"32⅞""","9¾""",NaN,4.49s,"36½""","120""",NaN,NaN,19 reps,"78""",NaN,NaN
3,A.J. Cann,ajcann2015,https://www.mockdraftable.com//player/aj-cann?...,2015,Offensive Guard,South Carolina,"6' 3""",313 lbs,"32⅝""","10¼""",NaN,NaN,NaN,NaN,NaN,NaN,26 reps,NaN,NaN,NaN
4,A.J. Derby,ajderby2015,https://www.mockdraftable.com//player/aj-derby...,2015,Tight End,Arkansas,"6' 4""",255 lbs,"30½""","9½""",NaN,NaN,NaN,NaN,NaN,NaN,15 reps,NaN,NaN,NaN

md_player_name
md_player_id
md_url
md_draft_class
md_position
md_college
md_height
md_weight
md_arm_length
md_hand_size
md_yard_10_split
md_yard_40_dash
md_vert_jump
md_broad_jump
md_cone_drill
md_yard_20_shuttle
md_bench_press
md_wing_span
md_yard_20_split
md_yard_60_shuttle

In [12]:
nfl_combine_df.dtypes

md_player_name        object
md_player_id          object
md_url                object
md_draft_class         int64
md_position           object
md_college            object
md_height             object
md_weight             object
md_arm_length         object
md_hand_size          object
md_yard_10_split      object
md_yard_40_dash       object
md_vert_jump          object
md_broad_jump         object
md_cone_drill         object
md_yard_20_shuttle    object
md_bench_press        object
md_wing_span          object
md_yard_20_split      object
md_yard_60_shuttle    object
dtype: object

In [13]:


for col in nfl_combine_df.select_dtypes(include="object").columns:
    nfl_combine_df[col] = nfl_combine_df[col].astype(str).apply(replace_fractions)

In [14]:
nfl_combine_df["md_weight_lbs"] = nfl_combine_df["md_weight"].apply(extract_number)

In [15]:
nfl_combine_df["md_height_in"] = nfl_combine_df["md_height"].apply(parse_height)

In [16]:
for col in ["md_arm_length", "md_hand_size", "md_wing_span"]:
    nfl_combine_df[col + "_in"] = nfl_combine_df[col].apply(extract_number)

# 40-dash, 10-yd split, cone drill, 20-yd shuttle --> float seconds
for col in ["md_yard_40_dash", "md_yard_20_split", "md_yard_60_shuttle", "md_yard_10_split", "md_cone_drill", "md_yard_20_shuttle"]:
    nfl_combine_df[col + "_sec"] = nfl_combine_df[col].apply(extract_number)

# vertical/broad jump --> decimal inches
for col in ["md_vert_jump", "md_broad_jump"]:
    nfl_combine_df[col + "_in"] = nfl_combine_df[col].apply(extract_number)

# Bench press
nfl_combine_df["md_bench_press_reps"] = nfl_combine_df["md_bench_press"].apply(extract_number)

display(nfl_combine_df.head())

,md_player_name,md_player_id,md_url,md_draft_class,md_position,md_college,md_height,md_weight,md_arm_length,md_hand_size,...,md_wing_span_in,md_yard_40_dash_sec,md_yard_20_split_sec,md_yard_60_shuttle_sec,md_yard_10_split_sec,md_cone_drill_sec,md_yard_20_shuttle_sec,md_vert_jump_in,md_broad_jump_in,md_bench_press_reps
0,A'Shawn Robinson,ashawnrobinson2016,https://www.mockdraftable.com//player/ashawn-r...,2016,Defensive Tackle,Alabama,"6' 4""",307 lbs,"34.5""","10.5""",...,NaN,5.20,NaN,NaN,1.78,7.8,4.74,26.0,106.0,22.0
1,A.C. Leonard,acleonard2014,https://www.mockdraftable.com//player/ac-leona...,2014,Tight End,Tennessee State,"6' 2""",252 lbs,"33""","9.25""",...,NaN,4.50,NaN,NaN,NaN,NaN,NaN,34.0,128.0,20.0
2,A.J. Brown,ajbrown2019,https://www.mockdraftable.com//player/aj-brown...,2019,Wide Receiver,Ole Miss,"6' 0.5""",226 lbs,"32.875""","9.75""",...,78.0,4.49,NaN,NaN,NaN,NaN,NaN,36.5,120.0,19.0
3,A.J. Cann,ajcann2015,https://www.mockdraftable.com//player/aj-cann?...,2015,Offensive Guard,South Carolina,"6' 3""",313 lbs,"32.625""","10.25""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0
4,A.J. Derby,ajderby2015,https://www.mockdraftable.com//player/aj-derby...,2015,Tight End,Arkansas,"6' 4""",255 lbs,"30.5""","9.5""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0

In [17]:
# Drop the original raw columns

raw_cols = [
    "md_weight", "md_height", "md_arm_length", "md_hand_size", "md_wing_span",
    "md_yard_40_dash", "md_yard_20_split", "md_yard_60_shuttle", "md_yard_10_split", "md_cone_drill", "md_yard_20_shuttle",
    "md_vert_jump", "md_broad_jump","md_bench_press"
]
nfl_combine_df.drop(columns=raw_cols, inplace=True, errors='ignore')

In [18]:
print(nfl_combine_df.dtypes)
print(nfl_combine_df.head())

md_player_name             object
md_player_id               object
md_url                     object
md_draft_class              int64
md_position                object
md_college                 object
md_weight_lbs             float64
md_height_in              float64
md_arm_length_in          float64
md_hand_size_in           float64
md_wing_span_in           float64
md_yard_40_dash_sec       float64
md_yard_20_split_sec      float64
md_yard_60_shuttle_sec    float64
md_yard_10_split_sec      float64
md_cone_drill_sec         float64
md_yard_20_shuttle_sec    float64
md_vert_jump_in           float64
md_broad_jump_in          float64
md_bench_press_reps       float64
dtype: object
     md_player_name        md_player_id  \
0  A'Shawn Robinson  ashawnrobinson2016
1      A.C. Leonard       acleonard2014
2        A.J. Brown         ajbrown2019
3         A.J. Cann          ajcann2015
4        A.J. Derby         ajderby2015

                                              md_url  md_draft_class  \
0  https://www.mockdraftable.com//player/ashawn-r...            2016
1  https://www.mockdraftable.com//player/ac-leona...            2014
2  https://www.mockdraftable.com//player/aj-brown...            2019
3  https://www.mockdraftable.com//player/aj-cann?...            2015
4  https://www.mockdraftable.com//player/aj-derby...            2015

        md_position       md_college  md_weight_lbs  md_height_in  \
0  Defensive Tackle          Alabama          307.0          72.0
1         Tight End  Tennessee State          252.0          72.0
2     Wide Receiver         Ole Miss          226.0          72.0
3   Offensive Guard   South Carolina          313.0          72.0
4         Tight End         Arkansas          255.0          72.0

   md_arm_length_in  md_hand_size_in  md_wing_span_in  md_yard_40_dash_sec  \
0            34.500            10.50              NaN                 5.20
1            33.000             9.25              NaN                 4.50
2            32.875             9.75             78.0                 4.49
3            32.625            10.25              NaN                  NaN
4            30.500             9.50              NaN                  NaN

   md_yard_20_split_sec  md_yard_60_shuttle_sec  md_yard_10_split_sec  \
0                   NaN                     NaN                  1.78
1                   NaN                     NaN                   NaN
2                   NaN                     NaN                   NaN
3                   NaN                     NaN                   NaN
4                   NaN                     NaN                   NaN

   md_cone_drill_sec  md_yard_20_shuttle_sec  md_vert_jump_in  \
0                7.8                    4.74             26.0
1                NaN                     NaN             34.0
2                NaN                     NaN             36.5
3                NaN                     NaN              NaN
4                NaN                     NaN              NaN

   md_broad_jump_in  md_bench_press_reps
0             106.0                 22.0
1             128.0                 20.0
2             120.0                 19.0
3               NaN                 26.0
4               NaN                 15.0

In [19]:
display(nfl_combine_df.head())

,md_player_name,md_player_id,md_url,md_draft_class,md_position,md_college,md_weight_lbs,md_height_in,md_arm_length_in,md_hand_size_in,md_wing_span_in,md_yard_40_dash_sec,md_yard_20_split_sec,md_yard_60_shuttle_sec,md_yard_10_split_sec,md_cone_drill_sec,md_yard_20_shuttle_sec,md_vert_jump_in,md_broad_jump_in,md_bench_press_reps
0,A'Shawn Robinson,ashawnrobinson2016,https://www.mockdraftable.com//player/ashawn-r...,2016,Defensive Tackle,Alabama,307.0,72.0,34.500,10.50,NaN,5.20,NaN,NaN,1.78,7.8,4.74,26.0,106.0,22.0
1,A.C. Leonard,acleonard2014,https://www.mockdraftable.com//player/ac-leona...,2014,Tight End,Tennessee State,252.0,72.0,33.000,9.25,NaN,4.50,NaN,NaN,NaN,NaN,NaN,34.0,128.0,20.0
2,A.J. Brown,ajbrown2019,https://www.mockdraftable.com//player/aj-brown...,2019,Wide Receiver,Ole Miss,226.0,72.0,32.875,9.75,78.0,4.49,NaN,NaN,NaN,NaN,NaN,36.5,120.0,19.0
3,A.J. Cann,ajcann2015,https://www.mockdraftable.com//player/aj-cann?...,2015,Offensive Guard,South Carolina,313.0,72.0,32.625,10.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0
4,A.J. Derby,ajderby2015,https://www.mockdraftable.com//player/aj-derby...,2015,Tight End,Arkansas,255.0,72.0,30.500,9.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0

In [20]:
nfl_combine_df.to_csv(data_folder / 'nfl_combine_data.csv', index=False)